# ========================================== #
#     MC-Shell UI & Design Tokens            #
# ========================================== #
# This file dictates the visual appearance, categories, and dropdown
# options for the Blockly frontend.

CAT_COLORS = {
    "Block": "#B06161",
    "Item": "#D4A373",
    "Material": "#D68C45",
    "Entity": "#8D7EB5",
    "Picker": "#95A5A6",
    "Geometry": "#5B7BA1",
    "Turtle": "#C9A65B",
    "LSystem": "#7A9473",
    "Events": "#D68C45",
    "Server": "#5C7457",
    "Digital Set": "#A57582",
    "Player": "#61A1B0",
    "World": "#5C7457",
    "Chat": "#D68C45",
}


# WOOD_TYPES = [
#     "OAK",
#     "SPRUCE",
#     "BIRCH",
#     "JUNGLE",
#     "ACACIA",
#     "DARK_OAK",
#     "MANGROVE",
#     "CHERRY",
#     "PALE_OAK",
#     "BAMBOO",
#     "CRIMSON",
#     "STRIPPED_ACACIA",
#     "STRIPPED_BIRCH",
#     "STRIPPED_CHERRY",
#     "STRIPPED_DARK_OAK",
#     "STRIPPED_JUNGLE",
#     "STRIPPED_MANGROVE",
#     "STRIPPED_OAK",
#     "STRIPPED_PALE_OAK",
#     "STRIPPED_SPRUCE",
# ]

# ARMOR_TYPES = [
#     "LEATHER",
#     "STONE",
#     "WOODEN",
#     "CHAINMAIL",
#     "IRON",
#     "GOLDEN",
#     "DIAMOND",
#     "NETHERITE",
#     "COPPER",
# ]

# TOOL_TYPES = ["WOODEN", "STONE", "IRON", "GOLDEN", "DIAMOND", "NETHERITE", "COPPER"]
# COLORS_LIST = [
#     "WHITE",
#     "ORANGE",
#     "MAGENTA",
#     "LIGHT_BLUE",
#     "YELLOW",
#     "LIME",
#     "PINK",
#     "GRAY",
#     "LIGHT_GRAY",
#     "CYAN",
#     "PURPLE",
#     "BLUE",
#     "BROWN",
#     "GREEN",
#     "RED",
#     "BLACK",
# ]

# COPPER_TYPES = [
#     'CUT_COPPER',
#     'EXPOSED_CUT_COPPER',
#     'WAXED_OXIDIZED_COPPER',
#     'WEATHERED_COPPER',
#     'WAXED_EXPOSED_COPPER',
#     'WAXED_WEATHERED_CUT_COPPER',
#     'WEATHERED_CUT_COPPER',
#     'WAXED_OXIDIZED_CUT_COPPER',
#     'WAXED_COPPER',
#     'OXIDIZED_COPPER',
#     'DEEPSLATE_COPPER',
#     'WAXED_EXPOSED_CUT_COPPER',
#     'RAW_COPPER',
#     'WAXED_WEATHERED_COPPER',
#     'OXIDIZED_CUT_COPPER',
#     'WAXED_CUT_COPPER',
#     'EXPOSED_COPPER'
# ]

# VARIANT_CONFIG = {
#     "WOOD": {
#         "id": "picker_wood_types",
#         "label": "Wood Type",
#         "prefixes": WOOD_TYPES,
#         "input_type": "MinecraftWood",
#         "shadow": "picker_wood_types",
#     },
#     "COPPER": {
#         "id": "picker_copper_types",
#         "label": "Copper Type",
#         "prefixes": COPPER_TYPES,
#         "input_type": "MinecraftCopper",
#         "shadow": "picker_copper_types",
#     },
#     "COLOR": {
#         "id": "picker_colours",
#         "label": "Color",
#         "prefixes": COLORS_LIST,
#         "input_type": "MinecraftColour",
#         "shadow": "picker_colours",
#     },
#     "ARMOR_TIER": {
#         "id": "picker_armor_tier",
#         "label": "Armor Tier",
#         "prefixes": ARMOR_TYPES,
#         "input_type": "MinecraftArmorTier",
#         "shadow": "picker_armor_tier",
#     },
#     "TOOL_TIER": {
#         "id": "picker_tool_tier",
#         "label": "Tool Tier",
#         "prefixes": TOOL_TYPES,
#         "input_type": "MinecraftToolTier",
#         "shadow": "picker_tool_tier",
#     },
# }

# MATERIAL_PICKER_GROUPS = {
#     "world": [
#         "AIR",
#         "STONE",
#         "GRANITE",
#         "DIORITE",
#         "ANDESITE",
#         "DEEPSLATE",
#         "CALCITE",
#         "TUFF",
#         "DIRT",
#         "COARSE_DIRT",
#         "ROOTED_DIRT",
#         "GRASS_BLOCK",
#         "PODZOL",
#         "MYCELIUM",
#         "DIRT_PATH",
#         "SAND",
#         "QUARTZ",
#         "RED_SAND",
#         "GRAVEL",
#         "CLAY",
#         "ICE",
#         "PACKED_ICE",
#         "BLUE_ICE",
#         "SNOW",
#         "SNOW_BLOCK",
#         "WATER",
#         "LAVA",
#         "BEDROCK",
#         "OBSIDIAN",
#         "CRYING_OBSIDIAN",
#         "MAGMA_BLOCK",
#     ],
#     "ores": [
#         "COAL_ORE",
#         "DEEPSLATE_COAL_ORE",
#         "IRON_ORE",
#         "DEEPSLATE_IRON_ORE",
#         "COPPER_ORE",
#         "DEEPSLATE_COPPER_ORE",
#         "GOLD_ORE",
#         "DEEPSLATE_GOLD_ORE",
#         "REDSTONE_ORE",
#         "DEEPSLATE_REDSTONE_ORE",
#         "EMERALD_ORE",
#         "DEEPSLATE_EMERALD_ORE",
#         "LAPIS_ORE",
#         "DEEPSLATE_LAPIS_ORE",
#         "DIAMOND_ORE",
#         "DEEPSLATE_DIAMOND_ORE",
#         "NETHER_GOLD_ORE",
#         "NETHER_QUARTZ_ORE",
#         "ANCIENT_DEBRIS",
#     ],
#     "woods_and_logs": [
#         "LOG",
#         "WOOD",
#         "PLANKS",
#         "SAPLING",
#         "LEAVES",
#         "STRIPPED_LOG",
#         "STRIPPED_WOOD",
#     ],
#     "colored_blocks": [
#         "WOOL",
#         "CARPET",
#         "TERRACOTTA",
#         "GLAZED_TERRACOTTA",
#         "CONCRETE",
#         "CONCRETE_POWDER",
#         "BED",
#         "BANNER",
#         "SHULKER_BOX",
#         "CANDLE",
#     ],
#     "stone_bricks": [
#         "BRICKS",
#         "STONE_BRICKS",
#         "MUD_BRICKS",
#         "DEEPSLATE_BRICKS",
#         "DEEPSLATE_TILES",
#         "NETHER_BRICKS",
#         "RED_NETHER_BRICKS",
#         "POLISHED_BLACKSTONE_BRICKS",
#         "END_STONE_BRICKS",
#         "QUARTZ_BRICKS",
#         "CHISELED_STONE_BRICKS",
#         "CRACKED_STONE_BRICKS",
#         "MOSSY_STONE_BRICKS",
#         "CHISELED_NETHER_BRICKS",
#         "CRACKED_NETHER_BRICKS",
#         "CHISELED_POLISHED_BLACKSTONE",
#         "CRACKED_POLISHED_BLACKSTONE_BRICKS",
#         "CHISELED_DEEPSLATE",
#         "CRACKED_DEEPSLATE_BRICKS",
#         "CRACKED_DEEPSLATE_TILES",
#         "CHISELED_TUFF_BRICKS",
#     ],
#     "glass": [
#         "GLASS",
#         "GLASS_PANE",
#         "TINTED_GLASS",
#         "STAINED_GLASS",
#         "STAINED_GLASS_PANE",
#     ],
#     "redstone_components": [
#         "REDSTONE",
#         "REDSTONE_WALL_TORCH",
#         "REDSTONE_WIRE",
#         "REDSTONE_BLOCK",
#         "REDSTONE_TORCH",
#         "REPEATER",
#         "COMPARATOR",
#         "PISTON",
#         "STICKY_PISTON",
#         "SLIME_BLOCK",
#         "HONEY_BLOCK",
#         "OBSERVER",
#         "DROPPER",
#         "DISPENSER",
#         "HOPPER",
#         "LECTERN",
#         "LEVER",
#         "DAYLIGHT_DETECTOR",
#         "TRIPWIRE_HOOK",
#         "TARGET",
#         "NOTE_BLOCK",
#         "RAIL",
#         "POWERED_RAIL",
#         "DETECTOR_RAIL",
#         "ACTIVATOR_RAIL",
#         "REDSTONE_LAMP",
#         "TRIPWIRE",
#     ],
#     "lighting": [
#         "TORCH",
#         "SOUL_TORCH",
#         "LANTERN",
#         "SOUL_LANTERN",
#         "GLOWSTONE",
#         "SEA_LANTERN",
#         "OCHRE_FROGLIGHT",
#         "PEARLESCENT_FROGLIGHT",
#         "VERDANT_FROGLIGHT",
#         "COPPER_LANTERN",
#         "SHROOMLIGHT",
#         "JACK_O_LANTERN",
#         "BEACON",
#         "END_ROD",
#     ],
#     "copper_variants": [
#         "COPPER_BLOCK",
#         "EXPOSED_COPPER",
#         "WEATHERED_COPPER",
#         "OXIDIZED_COPPER",
#         "CUT_COPPER",
#         "CHISELED_COPPER",
#         "COPPER_GRATE",
#         "COPPER_BULB",
#     ],
#     "nature": [
#         "MOSS_BLOCK",
#         "VINE",
#         "CAVE_VINES",
#         "TWISTING_VINES",
#         "WEEPING_VINES",
#         "LILY_PAD",
#         "SUGAR_CANE",
#         "BAMBOO",
#         "CACTUS",
#     ],
#     "flowers": [
#         "DANDELION",
#         "POPPY",
#         "BLUE_ORCHID",
#         "ALLIUM",
#         "AZURE_BLUET",
#         "RED_TULIP",
#         "ORANGE_TULIP",
#         "WHITE_TULIP",
#         "PINK_TULIP",
#         "OXEYE_DAISY",
#         "CORNFLOWER",
#         "LILY_OF_THE_VALLEY",
#         "WITHER_ROSE",
#         "SUNFLOWER",
#         "LILAC",
#         "ROSE_BUSH",
#         "PEONY",
#     ],
#     "functional_storage": [
#         "CHEST",
#         "TRAPPED_CHEST",
#         "BARREL",
#         "ENDER_CHEST",
#         "CRAFTER",
#         "FURNACE",
#         "BLAST_FURNACE",
#         "SMOKER",
#     ],
#     "spawning": ["SPAWNER", "TRIAL_SPAWNER", "FROGSPAWN", "RESPAWN_ANCHOR"],
#     # "tools": ["SWORD", "PICKAXE", "AXE", "SHOVEL", "HOE"],
#     # "armour": ["HELMET", "CHESTPLATE", "LEGGINGS", "BOOTS", "HORSE_ARMOR"],
#     "spawn_eggs": [
#         "ALLAY_SPAWN_EGG",
#         "ARMADILLO_SPAWN_EGG",
#         "AXOLOTL_SPAWN_EGG",
#         "BAT_SPAWN_EGG",
#         "BEE_SPAWN_EGG",
#         "BLAZE_SPAWN_EGG",
#         "BOGGED_SPAWN_EGG",
#         "BREEZE_SPAWN_EGG",
#         "CAMEL_HUSK_SPAWN_EGG",
#         "CAMEL_SPAWN_EGG",
#         "CAT_SPAWN_EGG",
#         "CAVE_SPIDER_SPAWN_EGG",
#         "CHICKEN_SPAWN_EGG",
#         "COD_SPAWN_EGG",
#         "COPPER_GOLEM_SPAWN_EGG",
#         "COW_SPAWN_EGG",
#         "CREAKING_SPAWN_EGG",
#         "CREEPER_SPAWN_EGG",
#         "DOLPHIN_SPAWN_EGG",
#         "DONKEY_SPAWN_EGG",
#         "DROWNED_SPAWN_EGG",
#         "ELDER_GUARDIAN_SPAWN_EGG",
#         "ENDER_DRAGON_SPAWN_EGG",
#         "ENDERMAN_SPAWN_EGG",
#         "ENDERMITE_SPAWN_EGG",
#         "EVOKER_SPAWN_EGG",
#         "FOX_SPAWN_EGG",
#         "FROG_SPAWN_EGG",
#         "FROGSPAWN",
#         "GHAST_SPAWN_EGG",
#         "GLOW_SQUID_SPAWN_EGG",
#         "GOAT_SPAWN_EGG",
#         "GUARDIAN_SPAWN_EGG",
#         "HAPPY_GHAST_SPAWN_EGG",
#         "HOGLIN_SPAWN_EGG",
#         "HORSE_SPAWN_EGG",
#         "HUSK_SPAWN_EGG",
#         "IRON_GOLEM_SPAWN_EGG",
#         "LLAMA_SPAWN_EGG",
#         "MAGMA_CUBE_SPAWN_EGG",
#         "MOOSHROOM_SPAWN_EGG",
#         "MULE_SPAWN_EGG",
#         "NAUTILUS_SPAWN_EGG",
#         "OCELOT_SPAWN_EGG",
#         "PANDA_SPAWN_EGG",
#         "PARCHED_SPAWN_EGG",
#         "PARROT_SPAWN_EGG",
#         "PHANTOM_SPAWN_EGG",
#         "PIG_SPAWN_EGG",
#         "PIGLIN_BRUTE_SPAWN_EGG",
#         "PIGLIN_SPAWN_EGG",
#         "PILLAGER_SPAWN_EGG",
#         "POLAR_BEAR_SPAWN_EGG",
#         "PUFFERFISH_SPAWN_EGG",
#         "RABBIT_SPAWN_EGG",
#         "RAVAGER_SPAWN_EGG",
#         "RESPAWN_ANCHOR",
#         "SALMON_SPAWN_EGG",
#         "SHEEP_SPAWN_EGG",
#         "SHULKER_SPAWN_EGG",
#         "SILVERFISH_SPAWN_EGG",
#         "SKELETON_HORSE_SPAWN_EGG",
#         "SKELETON_SPAWN_EGG",
#         "SLIME_SPAWN_EGG",
#         "SNIFFER_SPAWN_EGG",
#         "SNOW_GOLEM_SPAWN_EGG",
#         "SPAWNER",
#         "SPIDER_SPAWN_EGG",
#         "SQUID_SPAWN_EGG",
#         "STRAY_SPAWN_EGG",
#         "STRIDER_SPAWN_EGG",
#         "TADPOLE_SPAWN_EGG",
#         "TRADER_LLAMA_SPAWN_EGG",
#         "TRIAL_SPAWNER",
#         "TROPICAL_FISH_SPAWN_EGG",
#         "TURTLE_SPAWN_EGG",
#         "VEX_SPAWN_EGG",
#         "VILLAGER_SPAWN_EGG",
#         "VINDICATOR_SPAWN_EGG",
#         "WANDERING_TRADER_SPAWN_EGG",
#         "WARDEN_SPAWN_EGG",
#         "WITCH_SPAWN_EGG",
#         "WITHER_SKELETON_SPAWN_EGG",
#         "WITHER_SPAWN_EGG",
#         "WOLF_SPAWN_EGG",
#         "ZOGLIN_SPAWN_EGG",
#         "ZOMBIE_HORSE_SPAWN_EGG",
#         "ZOMBIE_NAUTILUS_SPAWN_EGG",
#         "ZOMBIE_SPAWN_EGG",
#         "ZOMBIE_VILLAGER_SPAWN_EGG",
#         "ZOMBIFIED_PIGLIN_SPAWN_EGG",
#     ],
#     "bars": [
#         "COPPER_BARS",
#         "EXPOSED_COPPER_BARS",
#         "IRON_BARS",
#         "OXIDIZED_COPPER_BARS",
#         "WAXED_COPPER_BARS",
#         "WAXED_EXPOSED_COPPER_BARS",
#         "WAXED_OXIDIZED_COPPER_BARS",
#         "WAXED_WEATHERED_COPPER_BARS",
#         "WEATHERED_COPPER_BARS",
#     ],
#     "chains":  ['COPPER_CHAIN', 'EXPOSED_COPPER_CHAIN', 'IRON_CHAIN', 'OXIDIZED_COPPER_CHAIN', 'WAXED_COPPER_CHAIN', 'WAXED_EXPOSED_COPPER_CHAIN', 'WAXED_OXIDIZED_COPPER_CHAIN', 'WAXED_WEATHERED_COPPER_CHAIN', 'WEATHERED_COPPER_CHAIN'],
#     "walls": [
#         "ANDESITE_WALL",
#         "BLACKSTONE_WALL",
#         "BRICK_WALL",
#         "COBBLED_DEEPSLATE_WALL",
#         "COBBLESTONE_WALL",
#         "DEEPSLATE_BRICK_WALL",
#         "DEEPSLATE_TILE_WALL",
#         "DIORITE_WALL",
#         "END_STONE_BRICK_WALL",
#         "GRANITE_WALL",
#         "MOSSY_COBBLESTONE_WALL",
#         "MOSSY_STONE_BRICK_WALL",
#         "MUD_BRICK_WALL",
#         "NETHER_BRICK_WALL",
#         "POLISHED_BLACKSTONE_BRICK_WALL",
#         "POLISHED_BLACKSTONE_WALL",
#         "POLISHED_DEEPSLATE_WALL",
#         "POLISHED_TUFF_WALL",
#         "PRISMARINE_WALL",
#         "RED_NETHER_BRICK_WALL",
#         "RED_SANDSTONE_WALL",
#         "RESIN_BRICK_WALL",
#         "SANDSTONE_WALL",
#         "STONE_BRICK_WALL",
#         "TUFF_BRICK_WALL",
#         "TUFF_WALL",
#     ],
#     "plants": [
#         "CAVE_VINES_PLANT",
#         "CHORUS_PLANT",
#         "KELP_PLANT",
#         "PITCHER_PLANT",
#         "TWISTING_VINES_PLANT",
#         "WEEPING_VINES_PLANT",
#     ],
#     "trims": [
#         "BOLT_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "COAST_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "DUNE_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "EYE_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "FLOW_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "HOST_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "RAISER_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "RIB_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "TIDE_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "VEX_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "WARD_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE",
#         "WILD_ARMOR_TRIM_SMITHING_TEMPLATE",
#     ],
#     "seeds": [
#         "BEETROOT_SEEDS",
#         "MELON_SEEDS",
#         "PUMPKIN_SEEDS",
#         "TORCHFLOWER_SEEDS",
#         "WHEAT_SEEDS",
#     ],
#     "charges": ["FIRE_CHARGE", "WIND_CHARGE"],
#     "fish": ["PUFFERFISH", "TROPICAL_FISH"],
#     "music": [
#         "JUKEBOX",
#         "MUSIC_DISC_11",
#         "MUSIC_DISC_13",
#         "MUSIC_DISC_5",
#         "MUSIC_DISC_BLOCKS",
#         "MUSIC_DISC_CAT",
#         "MUSIC_DISC_CHIRP",
#         "MUSIC_DISC_CREATOR",
#         "MUSIC_DISC_CREATOR_MUSIC_BOX",
#         "MUSIC_DISC_FAR",
#         "MUSIC_DISC_LAVA_CHICKEN",
#         "MUSIC_DISC_MALL",
#         "MUSIC_DISC_MELLOHI",
#         "MUSIC_DISC_OTHERSIDE",
#         "MUSIC_DISC_PIGSTEP",
#         "MUSIC_DISC_PRECIPICE",
#         "MUSIC_DISC_RELIC",
#         "MUSIC_DISC_STAL",
#         "MUSIC_DISC_STRAD",
#         "MUSIC_DISC_TEARS",
#         "MUSIC_DISC_WAIT",
#         "MUSIC_DISC_WARD",
#     ],
#     "food": [
#         "APPLE",
#         "BAKED_POTATO",
#         "BEEF",
#         "BEETROOT",
#         "BEETROOT_SOUP",
#         "BREAD",
#         "CARROT",
#         "CHICKEN",
#         "CHORUS_FRUIT",
#         "COD",
#         "COOKED_BEEF",
#         "COOKED_CHICKEN",
#         "COOKED_COD",
#         "COOKED_MUTTON",
#         "COOKED_PORKCHOP",
#         "COOKED_RABBIT",
#         "COOKED_SALMON",
#         "COOKIE",
#         "DRIED_KELP",
#         "ENCHANTED_GOLDEN_APPLE",
#         "GLOW_BERRIES",
#         "GOLDEN_APPLE",
#         "GOLDEN_CARROT",
#         "HONEY_BOTTLE",
#         "MELON_SLICE",
#         "MUSHROOM_STEW",
#         "MUTTON",
#         "POISONOUS_POTATO",
#         "PORKCHOP",
#         "POTATO",
#         "PUFFERFISH",
#         "PUMPKIN_PIE",
#         "RABBIT",
#         "RABBIT_STEW",
#         "ROTTEN_FLESH",
#         "SALMON",
#         "SPIDER_EYE",
#         "SUSPICIOUS_STEW",
#         "SWEET_BERRIES",
#         "TROPICAL_FISH",
#     ],
#     "various": [
#         "ANVIL",
#         "ARROW",
#         "AZALEA",
#         "BARRIER",
#         "BASALT",
#         "BEEHIVE",
#         "BEETROOT",
#         "BEETROOTS",
#         "BELL",
#         "BLACKSTONE",
#         "BONE",
#         "BOOK",
#         "BOOKSHELF",
#         "BOW",
#         "BOWL",
#         "BRICK",
#         "BRUSH",
#         "BUNDLE",
#         "BUSH",
#         "CAMPFIRE",
#         "CAULDRON",
#         "CLOCK",
#         "COAL",
#         "COMPASS",
#         "COMPOSTER",
#         "CONDUIT",
#         "CROSSBOW",
#         "DIAMOND",
#         "ELYTRA",
#         "EMERALD",
#         "FARMLAND",
#         "FEATHER",
#         "FERN",
#         "FIRE",
#         "FLINT",
#         "GRINDSTONE",
#         "GUNPOWDER",
#         "JIGSAW",
#         "LADDER",
#         "LEAD",
#         "LEATHER",
#         "LIGHT",
#         "LODESTONE",
#         "LOOM",
#         "MACE",
#         "MAP",
#         "MUD",
#         "NETHERRACK",
#         "PAINTING",
#         "PAPER",
#         "POTION",
#         "PRISMARINE",
#         "PUFFERFISH",
#         "QUARTZ",
#         "RABBIT",
#         "SADDLE",
#         "SALMON",
#         "SANDSTONE",
#         "SCAFFOLDING",
#         "SCULK",
#         "SEAGRASS",
#         "SHEARS",
#         "SHIELD",
#         "SNOWBALL",
#         "SPONGE",
#         "SPYGLASS",
#         "STICK",
#         "STONECUTTER",
#         "STRING",
#         "TNT",
#         "TORCHFLOWER",
#         "TRIDENT",
#         "VAULT",
#         "WILDFLOWERS",
#     ],
#     "buckets": [
#         "BUCKET",
#         "AXOLOTL_BUCKET",
#         "COD_BUCKET",
#         "LAVA_BUCKET",
#         "MILK_BUCKET",
#         "POWDER_SNOW_BUCKET",
#         "PUFFERFISH_BUCKET",
#         "SALMON_BUCKET",
#         "TADPOLE_BUCKET",
#         "TROPICAL_FISH_BUCKET",
#         "WATER_BUCKET",
#     ],
#     "books": ["ENCHANTED_BOOK", "KNOWLEDGE_BOOK", "WRITABLE_BOOK", "WRITTEN_BOOK"],
#     "miscelleneous": [
#         "AMETHYST_BLOCK",
#         "BAMBOO_BLOCK",
#         "BONE_BLOCK",
#         "BRAIN_CORAL_BLOCK",
#         "BROWN_MUSHROOM_BLOCK",
#         "BUBBLE_CORAL_BLOCK",
#         "CHISELED_QUARTZ_BLOCK",
#         "COAL_BLOCK",
#         "DEAD_BRAIN_CORAL_BLOCK",
#         "DEAD_BUBBLE_CORAL_BLOCK",
#         "DEAD_FIRE_CORAL_BLOCK",
#         "DEAD_HORN_CORAL_BLOCK",
#         "DEAD_TUBE_CORAL_BLOCK",
#         "DRIED_KELP_BLOCK",
#         "DRIPSTONE_BLOCK",
#         "EMERALD_BLOCK",
#         "FIRE_CORAL_BLOCK",
#         "GOLD_BLOCK",
#         "HAY_BLOCK",
#         "HONEYCOMB_BLOCK",
#         "HORN_CORAL_BLOCK",
#         "LAPIS_BLOCK",
#         "NETHER_WART_BLOCK",
#         "PALE_MOSS_BLOCK",
#         "PURPUR_BLOCK",
#         "QUARTZ_BLOCK",
#         "RAW_COPPER_BLOCK",
#         "RAW_GOLD_BLOCK",
#         "RAW_IRON_BLOCK",
#         "RED_MUSHROOM_BLOCK",
#         "RESIN_BLOCK",
#         "STRIPPED_BAMBOO_BLOCK",
#         "STRUCTURE_BLOCK",
#         "TEST_BLOCK",
#         "TEST_INSTANCE_BLOCK",
#         "TUBE_CORAL_BLOCK",
#         "WARPED_WART_BLOCK",
#         "WAXED_COPPER_BLOCK",
#     ],
#     "commands": [
#         "COMMAND_BLOCK",
#         "REPEATING_COMMAND_BLOCK",
#         "CHAIN_COMMAND_BLOCK",
#     ],
    # "copper":
    # [
    # 'CUT_COPPER_SLAB',
    # 'CUT_COPPER_STAIRS',
    # 'EXPOSED_COPPER_BULB',
    # 'EXPOSED_COPPER_CHAIN',
    # 'EXPOSED_COPPER_CHEST',
    # 'EXPOSED_COPPER_DOOR',
    # 'EXPOSED_COPPER_GOLEM_STATUE',
    # 'EXPOSED_COPPER_GRATE',
    # 'EXPOSED_COPPER_LANTERN',
    # 'EXPOSED_COPPER_TRAPDOOR',
    # 'EXPOSED_CUT_COPPER_SLAB',
    # 'EXPOSED_CUT_COPPER_STAIRS',
    # 'OXIDIZED_COPPER_BULB',
    # 'OXIDIZED_COPPER_CHAIN',
    # 'OXIDIZED_COPPER_CHEST',
    # 'OXIDIZED_COPPER_DOOR',
    # 'OXIDIZED_COPPER_GOLEM_STATUE',
    # 'OXIDIZED_COPPER_GRATE',
    # 'OXIDIZED_COPPER_LANTERN',
    # 'OXIDIZED_COPPER_TRAPDOOR',
    # 'OXIDIZED_CUT_COPPER_SLAB',
    # 'OXIDIZED_CUT_COPPER_STAIRS',
    # 'RAW_COPPER_BLOCK',
    # 'WAXED_COPPER_BLOCK',
    # 'WAXED_COPPER_BULB',
    # 'WAXED_COPPER_CHAIN',
    # 'WAXED_COPPER_CHEST',
    # 'WAXED_COPPER_DOOR',
    # 'WAXED_COPPER_GOLEM_STATUE',
    # 'WAXED_COPPER_GRATE',
    # 'WAXED_COPPER_LANTERN',
    # 'WAXED_COPPER_TRAPDOOR',
    # 'WAXED_CUT_COPPER_SLAB',
    # 'WAXED_CUT_COPPER_STAIRS',
    # 'WAXED_EXPOSED_COPPER_BULB',
    # 'WAXED_EXPOSED_COPPER_CHAIN',
    # 'WAXED_EXPOSED_COPPER_CHEST',
    # 'WAXED_EXPOSED_COPPER_DOOR',
    # 'WAXED_EXPOSED_COPPER_GOLEM_STATUE',
    # 'WAXED_EXPOSED_COPPER_GRATE',
    # 'WAXED_EXPOSED_COPPER_LANTERN',
    # 'WAXED_EXPOSED_COPPER_TRAPDOOR',
    # 'WAXED_EXPOSED_CUT_COPPER_SLAB',
    # 'WAXED_EXPOSED_CUT_COPPER_STAIRS',
    # 'WAXED_OXIDIZED_COPPER_BULB',
    # 'WAXED_OXIDIZED_COPPER_CHAIN',
    # 'WAXED_OXIDIZED_COPPER_CHEST',
    # 'WAXED_OXIDIZED_COPPER_DOOR',
    # 'WAXED_OXIDIZED_COPPER_GOLEM_STATUE',
    # 'WAXED_OXIDIZED_COPPER_GRATE',
    # 'WAXED_OXIDIZED_COPPER_LANTERN',
    # 'WAXED_OXIDIZED_COPPER_TRAPDOOR',
    # 'WAXED_OXIDIZED_CUT_COPPER_SLAB',
    # 'WAXED_OXIDIZED_CUT_COPPER_STAIRS',
    # 'WAXED_WEATHERED_COPPER_BULB',
    # 'WAXED_WEATHERED_COPPER_CHAIN',
    # 'WAXED_WEATHERED_COPPER_CHEST',
    # 'WAXED_WEATHERED_COPPER_DOOR',
    # 'WAXED_WEATHERED_COPPER_GOLEM_STATUE',
    # 'WAXED_WEATHERED_COPPER_GRATE',
    # 'WAXED_WEATHERED_COPPER_LANTERN',
    # 'WAXED_WEATHERED_COPPER_TRAPDOOR',
    # 'WAXED_WEATHERED_CUT_COPPER_SLAB',
    # 'WAXED_WEATHERED_CUT_COPPER_STAIRS',
    # 'WEATHERED_COPPER_BULB',
    # 'WEATHERED_COPPER_CHAIN',
    # 'WEATHERED_COPPER_CHEST',
    # 'WEATHERED_COPPER_DOOR',
    # 'WEATHERED_COPPER_GOLEM_STATUE',
    # 'WEATHERED_COPPER_GRATE',
    # 'WEATHERED_COPPER_LANTERN',
    # 'WEATHERED_COPPER_TRAPDOOR',
    # 'WEATHERED_CUT_COPPER_SLAB',
    # 'WEATHERED_CUT_COPPER_STAIRS'
    # 'EXPOSED_CHISELED_COPPER',
    # 'EXPOSED_CUT_COPPER',
    # 'OXIDIZED_CHISELED_COPPER',
    # 'OXIDIZED_CUT_COPPER',
    # 'RAW_COPPER',
    # 'WAXED_CHISELED_COPPER',
    # 'WAXED_CUT_COPPER',
    # 'WAXED_EXPOSED_CHISELED_COPPER',
    # 'WAXED_EXPOSED_COPPER',
    # 'WAXED_EXPOSED_CUT_COPPER',
    # 'WAXED_OXIDIZED_CHISELED_COPPER',
    # 'WAXED_OXIDIZED_COPPER',
    # 'WAXED_OXIDIZED_CUT_COPPER',
    # 'WAXED_WEATHERED_CHISELED_COPPER',
    # 'WAXED_WEATHERED_COPPER',
    # 'WAXED_WEATHERED_CUT_COPPER',
    # 'WEATHERED_CHISELED_COPPER',
    # 'WEATHERED_CUT_COPPER'
    # ]
# }


# ENTITY_GROUPS = {
#     "passive_mobs": [
#         "ALLAY",
#         "ARMADILLO",
#         "AXOLOTL",
#         "BAT",
#         "CAMEL",
#         "CAT",
#         "CHICKEN",
#         "COD",
#         "COW",
#         "DONKEY",
#         "FOX",
#         "FROG",
#         "GLOW_SQUID",
#         "HORSE",
#         "MOOSHROOM",
#         "MULE",
#         "OCELOT",
#         "PANDA",
#         "PARROT",
#         "PIG",
#         "POLAR_BEAR",
#         "PUFFERFISH",
#         "RABBIT",
#         "SALMON",
#         "SHEEP",
#         "SNIFFER",
#         "SQUID",
#         "STRIDER",
#         "TADPOLE",
#         "TROPICAL_FISH",
#         "TURTLE",
#         "VILLAGER",
#         "WANDERING_TRADER",
#         "WOLF",
#     ],
#     "hostile_mobs": [
#         "BLAZE",
#         "BOGGED",
#         "BREEZE",
#         "CAVE_SPIDER",
#         "CREAKING",
#         "CREEPER",
#         "DROWNED",
#         "ELDER_GUARDIAN",
#         "ENDERMAN",
#         "ENDERMITE",
#         "EVOKER",
#         "GHAST",
#         "GUARDIAN",
#         "HOGLIN",
#         "HUSK",
#         "ILLUSIONER",
#         "MAGMA_CUBE",
#         "PHANTOM",
#         "PIGLIN",
#         "PIGLIN_BRUTE",
#         "PILLAGER",
#         "RAVAGER",
#         "SHULKER",
#         "SILVERFISH",
#         "SKELETON",
#         "SLIME",
#         "SPIDER",
#         "STRAY",
#         "VEX",
#         "VINDICATOR",
#         "WARDEN",
#         "WITCH",
#         "WITHER",
#         "WITHER_SKELETON",
#         "ZOGLIN",
#         "ZOMBIE",
#         "ZOMBIE_VILLAGER",
#         "ZOMBIFIED_PIGLIN",
#     ],
#     "minecarts": [
#         "MINECART",
#         "CHEST_MINECART",
#         "COMMAND_BLOCK_MINECART",
#         "FURNACE_MINECART",
#         "HOPPER_MINECART",
#         "SPAWNER_MINECART",
#         "TNT_MINECART",
#     ],
#     "projectiles": [
#         "ARROW",
#         "EGG",
#         "ENDER_PEARL",
#         "EXPERIENCE_BOTTLE",
#         "FIREBALL",
#         "FIREWORK_ROCKET",
#         "SNOWBALL",
#         "TRIDENT",
#     ],
#     "utility": [
#         "ARMOR_STAND",
#         "END_CRYSTAL",
#         "EXPERIENCE_ORB",
#         "FALLING_BLOCK",
#         "ITEM_FRAME",
#         "PAINTING",
#         "PLAYER",
#     ],
# }

TYPE_MAP = {
    "str": "String",
    "int": "Number",
    "float": "Number",
    "bool": "Boolean",
    "list": "Array",
    "tuple": "List",
    "Vec3": "3DVector",
    "Matrix3": "3DMatrix",
    "Block": "Block",
    "Material":"Material",
    "Item":"Item",
    "DigitalSet": "Digital_Set",
    "Metric": "Metric",
    "QDirection": "QDirection",
    "Axis": "Axis",
    "QCompass": "QCompass",
    "Time": "Time",
    "TimeType": "TimeType",
    "Weather": "Weather",
    "Difficulty": "Difficulty",
    "Gamemode": "Gamemode",
    "GameRule": "GameRule",
    "LocateType": "LocateType",
    "Structure": "Structure",
    "Biome": "Biome",
    "Poi": "Poi",
    "Entity": "Entity",
    "Effect": "Effect",
    "DataPath": "DataPath",
}

SHADOW_MAP = dict(

    Block='<shadow type="mc_block_picker_world"><field name="VALUE">STONE</field></shadow>',
    Item='<shadow type="mc_item_picker_food"><field name="VALUE">APPLE</field></shadow>',
    Entity='<shadow type="mc_entity_picker_passive_mobs"><field name="VALUE">PIG</field></shadow>',

    int='<shadow type="math_number"><field name="NUM">1</field></shadow>',
    float='<shadow type="math_number"><field name="NUM">1.0</field></shadow>',
    bool='<shadow type="logic_boolean"><field name="BOOL">TRUE</field></shadow>',
    math_number='<shadow type="math_number"><field name="NUM">1</field></shadow>',
    str='<shadow type="text"><field name="TEXT"></field></shadow>',
    text='<shadow type="text"><field name="TEXT"></field></shadow>',
    Vec3='<shadow type="minecraft_vector_3d"><value name="X"><shadow type="math_number"><field name="NUM">0</field></shadow></value><value name="Y"><shadow type="math_number"><field name="NUM">0</field></shadow></value><value name="Z"><shadow type="math_number"><field name="NUM">0</field></shadow></value></shadow>',
    Matrix3='<shadow type="minecraft_matrix_3d_euler"></shadow>',
    Metric='<shadow type="picker_metric"><field name="VALUE">euclidean</field></shadow>',
    QHeading='<shadow type="picker_qheading"><field name="VALUE">F</field></shadow>',
    Axis='<shadow type="picker_axis"><field name="VALUE">y</field></shadow>',
    QCompass='<shadow type="picker_qcompass"><field name="VALUE">N</field></shadow>',
    Time='<shadow type="picker_time"><field name="VALUE">day</field></shadow>',
    TimeType='<shadow type="picker_timetype"><field name="VALUE">gametime</field></shadow>',
    Weather='<shadow type="picker_weather"><field name="VALUE">clear</field></shadow>',
    Difficulty='<shadow type="picker_difficulty"><field name="VALUE">normal</field></shadow>',
    GameMode='<shadow type="picker_gamemode"><field name="VALUE">creative</field></shadow>',
    GameRule='<shadow type="picker_gamerule"><field name="VALUE">advance_time</field></shadow>',
    IntegerGameRule='<shadow type="picker_integergamerule"><field name="VALUE">respawn_radius</field></shadow>',
    LocateType='<shadow type="picker_locatetype"><field name="VALUE">structure</field></shadow>',
    Structure='<shadow type="picker_structure"><field name="VALUE">ancient_city</field></shadow>',
    Biome='<shadow type="picker_biome"><field name="VALUE">badlands</field></shadow>',
    Poi='<shadow type="picker_poi"><field name="VALUE">armorer</field></shadow>',
    Effect='<shadow type="picker_effect"><field name="VALUE">speed</field></shadow>',
    TitleAction='<shadow type="picker_titleaction"><field name="VALUE">reset</field></shadow>',
    DataPath='<shadow type="picker_data_path"><field name="VALUE">Pos</field></shadow>',
)

DATA_PATHS = [
    ("Brain", "Brain"),
    ("Hurt By Timestamp", "HurtByTimestamp"),
    ("Sleep Timer", "SleepTimer"),
    ("Attributes", "Attributes"),
    ("Invulnerable", "Invulnerable"),
    ("Fall Flying", "FallFlying"),
    ("Portal Cooldown", "PortalCooldown"),
    ("Absorption Amount", "AbsorptionAmount"),
    ("Abilities", "abilities"),
    ("Fall Distance", "FallDistance"),
    ("Recipe Book", "recipeBook"),
    ("Death Time", "DeathTime"),
    ("Xp Seed", "XpSeed"),
    ("Xp Total", "XpTotal"),
    ("UUID", "UUID"),
    ("Player Game Type", "playerGameType"),
    ("Seen Credits", "seenCredits"),
    ("Motion", "Motion"),
    ("Health", "Health"),
    ("Food Saturation Level", "foodSaturationLevel"),
    ("Air", "Air"),
    ("On Ground", "OnGround"),
    ("Dimension", "Dimension"),
    ("Rotation", "Rotation"),
    ("Xp Level", "XpLevel"),
    ("Score", "Score"),
    ("Pos", "Pos"),
    ("Previous Player Game Type", "previousPlayerGameType"),
    ("Fire", "Fire"),
    ("Xp P", "XpP"),
    ("Ender Items", "EnderItems"),
    ("Data Version", "DataVersion"),
    ("Food Level", "foodLevel"),
    ("Food Exhaustion Level", "foodExhaustionLevel"),
    ("Hurt Time", "HurtTime"),
    ("Selected Item Slot", "SelectedItemSlot"),
    ("Inventory", "Inventory"),
    ("Food Tick Timer", "foodTickTimer"),
]

TIMETYPES = [("Day Time", "daytime"), ("Game Time", "gametime"), ("Day", "day")]
WEATHERS = [("Clear", "clear"), ("Rain", "rain"), ("Thunder", "thunder")]
DIFFICULTYS = [
    ("Peaceful", "peaceful"),
    ("Easy", "easy"),
    ("Normal", "normal"),
    ("Hard", "hard"),
]
GAMEMODES = [
    ("Survival", "survival"),
    ("Creative", "creative"),
    ("Adventure", "adventure"),
    ("Spectator", "spectator"),
]
LOCATETYPES = [
    ("Structure", "structure"),
    ("Biome", "biome"),
    ("Point of Interest (POI)", "poi"),
]
METRICS = [
    ("Euclidean", "euclidean"),
    ("Manhattan", "manhattan"),
    ("Chebyshev", "chebyshev"),
]
AXES = [("Yaw (Y)", "y"), ("Pitch (X)", "x"), ("Roll (Z)", "z")]
COMPASS = [
    ("North (-Z)", "N"),
    ("South (+Z)", "S"),
    ("East (+X)", "E"),
    ("West (-X)", "W"),
    ("North-East", "NE"),
    ("North-West", "NW"),
    ("South-East", "SE"),
    ("South-West", "SW"),
]
QHEADINGS = [
    ("Forward", "F"),
    ("Back", "B"),
    ("Right", "R"),
    ("Left", "L"),
    ("Up", "U"),
    ("Down", "D"),
    ("Forward-Right", "FR"),
    ("Forward-Left", "FL"),
    ("Back-Right", "BR"),
    ("Back-Left", "BL"),
    ("Forward-Up", "FU"),
    ("Forward-Down", "FD"),
    ("Back-Up", "BU"),
    ("Back-Down", "BD"),
    ("Right-Up", "RU"),
    ("Right-Down", "RD"),
    ("Left-Up", "LU"),
    ("Left-Down", "LD"),
    ("Forward-Right-Up", "FRU"),
    ("Forward-Right-Down", "FRD"),
    ("Forward-Left-Up", "FLU"),
    ("Forward-Left-Down", "FLD"),
    ("Back-Right-Up", "BRU"),
    ("Back-Right-Down", "BRD"),
    ("Back-Left-Up", "BLU"),
    ("Back-Left-Down", "BLD"),
]
QCOMPASS = [
    ("North (-Z)", "N"),
    ("South (+Z)", "S"),
    ("East (+X)", "E"),
    ("West (-X)", "W"),
    ("Up (+Y)", "U"),
    ("Down (-Y)", "D"),
    ("North-East", "NE"),
    ("North-West", "NW"),
    ("South-East", "SE"),
    ("South-West", "SW"),
    ("North-Up", "NU"),
    ("North-Down", "ND"),
    ("South-Up", "SU"),
    ("South-Down", "SD"),
    ("East-Up", "EU"),
    ("East-Down", "ED"),
    ("West-Up", "WU"),
    ("West-Down", "WD"),
    ("North-East-Up", "NEU"),
    ("North-East-Down", "NED"),
    ("North-West-Up", "NWU"),
    ("North-West-Down", "NWD"),
    ("South-East-Up", "SEU"),
    ("South-East-Down", "SED"),
    ("South-West-Up", "SWU"),
    ("South-West-Down", "SWD"),
]
TIMES = [
    ("Day (1000)", "day"),
    ("Noon (6000)", "noon"),
    ("Night (13000)", "night"),
    ("Midnight (18000)", "midnight"),
]

STRUCTURES = [
    ("Ancient City", "ancient_city"),
    ("Bastion Remnant", "bastion_remnant"),
    ("Buried Treasure", "buried_treasure"),
    ("Desert Pyramid", "desert_pyramid"),
    ("End City", "end_city"),
    ("Fortress", "fortress"),
    ("Igloo", "igloo"),
    ("Jungle Pyramid", "jungle_pyramid"),
    ("Mansion", "mansion"),
    ("Mineshaft", "mineshaft"),
    ("Monument", "monument"),
    ("Nether Fossil", "nether_fossil"),
    ("Ocean Ruin", "ocean_ruin"),
    ("Pillager Outpost", "pillager_outpost"),
    ("Ruined Portal", "ruined_portal"),
    ("Shipwreck", "shipwreck"),
    ("Stronghold", "stronghold"),
    ("Swamp Hut", "swamp_hut"),
    ("Village", "village"),
    ("Woodland Mansion", "mansion"),
]
BIOMES = [
    ("Badlands", "badlands"),
    ("Bamboo Jungle", "bamboo_jungle"),
    ("Beach", "beach"),
    ("Birch Forest", "birch_forest"),
    ("Cherry Grove", "cherry_grove"),
    ("Dark Forest", "dark_forest"),
    ("Deep Dark", "deep_dark"),
    ("Desert", "desert"),
    ("Dripstone Caves", "dripstone_caves"),
    ("End Highlands", "end_highlands"),
    ("End Midlands", "end_midlands"),
    ("Forest", "forest"),
    ("Frozen Peaks", "frozen_peaks"),
    ("Grove", "grove"),
    ("Ice Spikes", "ice_spikes"),
    ("Jagged Peaks", "jagged_peaks"),
    ("Jungle", "jungle"),
    ("Lush Caves", "lush_caves"),
    ("Mangrove Swamp", "mangrove_swamp"),
    ("Meadow", "meadow"),
    ("Mushroom Fields", "mushroom_fields"),
    ("Nether Wastes", "nether_wastes"),
    ("Ocean", "ocean"),
    ("Plains", "plains"),
    ("River", "river"),
    ("Savanna", "savanna"),
    ("Snowy Beach", "snowy_beach"),
    ("Snowy Plains", "snowy_plains"),
    ("Snowy Taiga", "snowy_taiga"),
    ("Soul Sand Valley", "soul_sand_valley"),
    ("Stony Peaks", "stony_peaks"),
    ("Swamp", "swamp"),
    ("Taiga", "taiga"),
    ("The End", "the_end"),
    ("The Void", "the_void"),
    ("Warm Ocean", "warm_ocean"),
    ("Warped Forest", "warped_forest"),
]
POIS = [
    ("Armorer", "armorer"),
    ("Butcher", "butcher"),
    ("Cartographer", "cartographer"),
    ("Cleric", "cleric"),
    ("Farmer", "farmer"),
    ("Fisherman", "fisherman"),
    ("Fletcher", "fletcher"),
    ("Leatherworker", "leatherworker"),
    ("Librarian", "librarian"),
    ("Mason", "mason"),
    ("Shepherd", "shepherd"),
    ("Toolsmith", "toolsmith"),
    ("Weaponsmith", "weaponsmith"),
    ("Beehive", "beehive"),
    ("Bee Nest", "bee_nest"),
    ("End Portal", "end_portal"),
    ("Home", "home"),
    ("Lightning Rod", "lightning_rod"),
    ("Lodestone", "lodestone"),
    ("Meeting", "meeting"),
    ("Nether Portal", "nether_portal"),
]
GAMERULES = [
    ("Advance Time", "advance_time"),
    ("Advance Weather", "advance_weather"),
    ("Allow Entering Nether", "allow_entering_nether_using_portals"),
    ("Block Drops", "block_drops"),
    ("Block Explosion Drop Decay", "block_explosion_drop_decay"),
    ("Command Block Output", "command_block_output"),
    ("Command Blocks Work", "command_blocks_work"),
    ("Disable Elytra Movement Check", "elytra_movement_check"),
    ("Disable Raids", "raids"),
    ("Do Entity Drops", "entity_drops"),
    ("Drowning Damage", "drowning_damage"),
    ("Ender Pearls Vanish On Death", "ender_pearls_vanish_on_death"),
    ("Fall Damage", "fall_damage"),
    ("Fire Damage", "fire_damage"),
    ("Forgive Dead Players", "forgive_dead_players"),
    ("Freeze Damage", "freeze_damage"),
    ("Global Sound Events", "global_sound_events"),
    ("Immediate Respawn", "immediate_respawn"),
    ("Keep Inventory", "keep_inventory"),
    ("Lava Source Conversion", "lava_source_conversion"),
    ("Limit Crafting", "limited_crafting"),
    ("Locator Bar", "locator_bar"),
    ("Log Admin Commands", "log_admin_commands"),
    ("Mob Drops", "mob_drops"),
    ("Mob Explosion Drop Decay", "mob_explosion_drop_decay"),
    ("Mob Griefing", "mob_griefing"),
    ("Natural Health Regeneration", "natural_health_regeneration"),
    ("Player Movement Check", "player_movement_check"),
    ("Projectiles Can Break Blocks", "projectiles_can_break_blocks"),
    ("PVP", "pvp"),
    ("Reduced Debug Info", "reduced_debug_info"),
    ("Send Command Feedback", "send_command_feedback"),
    ("Show Advancement Messages", "show_advancement_messages"),
    ("Show Death Messages", "show_death_messages"),
    ("Spawn Mobs", "spawn_mobs"),
    ("Spawn Monsters", "spawn_monsters"),
    ("Spawn Patrols", "spawn_patrols"),
    ("Spawn Phantoms", "spawn_phantoms"),
    ("Spawn Wandering Traders", "spawn_wandering_traders"),
    ("Spawn Wardens", "spawn_wardens"),
    ("Spawner Blocks Work", "spawner_blocks_work"),
    ("Spectators Generate Chunks", "spectators_generate_chunks"),
    ("Spread Vines", "spread_vines"),
    ("TNT Explodes", "tnt_explodes"),
    ("TNT Explosion Drop Decay", "tnt_explosion_drop_decay"),
    ("Universal Anger", "universal_anger"),
    ("Water Source Conversion", "water_source_conversion"),
]
INTEGERGAMERULES = [
    ("Fire Spread Radius", "fire_spread_radius_around_player"),
    ("Max Block Modifications", "max_block_modifications"),
    ("Max Command Forks", "max_command_forks"),
    ("Max Command Sequence Length", "max_command_sequence_length"),
    ("Max Entity Cramming", "max_entity_cramming"),
    ("Max Snow Accumulation Height", "max_snow_accumulation_height"),
    ("Players Nether Portal Creative Delay", "players_nether_portal_creative_delay"),
    ("Players Nether Portal Default Delay", "players_nether_portal_default_delay"),
    ("Players Sleeping Percentage", "players_sleeping_percentage"),
    ("Random Tick Speed", "random_tick_speed"),
    ("Respawn Radius", "respawn_radius"),
]
EFFECTS = [
    ("Speed", "speed"),
    ("Slowness", "slowness"),
    ("Haste", "haste"),
    ("Strength", "strength"),
    ("Instant Health", "instant_health"),
    ("Instant Damage", "instant_damage"),
    ("Jump Boost", "jump_boost"),
    ("Regeneration", "regeneration"),
    ("Resistance", "resistance"),
    ("Fire Resistance", "fire_resistance"),
    ("Water Breathing", "water_breathing"),
    ("Invisibility", "invisibility"),
    ("Blindness", "blindness"),
    ("Night Vision", "night_vision"),
    ("Hunger", "hunger"),
    ("Weakness", "weakness"),
    ("Poison", "poison"),
    ("Wither", "wither"),
    ("Health Boost", "health_boost"),
    ("Absorption", "absorption"),
    ("Saturation", "saturation"),
    ("Glowing", "glowing"),
    ("Levitation", "levitation"),
    ("Luck", "luck"),
    ("Unluck", "unluck"),
    ("Slow Falling", "slow_falling"),
    ("Conduit Power", "conduit_power"),
    ("Dolphins Grace", "dolphins_grace"),
    ("Bad Omen", "bad_omen"),
    ("Hero of the Village", "hero_of_the_village"),
    ("Darkness", "darkness"),
]
TITLEACTIONS = [
    ("Main Title", "title"),
    ("Subtitle", "subtitle"),
    ("Action Bar", "actionbar"),
    ("Clear", "clear"),
    ("Reset", "reset"),
]
GENERATED_ACTION_PICKERS = [
    {
        "id": "picker_qheading",
        "label": "Local Q-Heading",
        "options": QHEADINGS,
        "input_type": "QHeading",
    },
    {"id": "picker_axis", "label": "Axis", "options": AXES, "input_type": "Axis"},
    {
        "id": "picker_qcompass",
        "label": "Global Q-Compass Direction",
        "options": QCOMPASS,
        "input_type": "QCompass",
    },

]

ACTION_PICKERS = [
    {
        "id": "picker_timetype",
        "label": "Time Type",
        "options": TIMETYPES,
        "input_type": "TimeType",
    },
    {"id": "picker_time", "label": "Time", "options": TIMES, "input_type": "Time"},
    {
        "id": "picker_weather",
        "label": "Weather",
        "options": WEATHERS,
        "input_type": "Weather",
    },
    {
        "id": "picker_difficulty",
        "label": "Difficulty",
        "options": DIFFICULTYS,
        "input_type": "Difficulty",
    },
    {
        "id": "picker_gamemode",
        "label": "Game Mode",
        "options": GAMEMODES,
        "input_type": "GameMode",
    },
    {
        "id": "picker_gamerule",
        "label": "Game Rule",
        "options": GAMERULES,
        "input_type": "GameRule",
    },
    {
        "id": "picker_integergamerule",
        "label": "Integer Game Rule",
        "options": INTEGERGAMERULES,
        "input_type": "IntegerGameRule",
    },
    {
        "id": "picker_locatetype",
        "label": "Locate Type",
        "options": LOCATETYPES,
        "input_type": "LocateType",
    },
    {
        "id": "picker_structure",
        "label": "Structure",
        "options": STRUCTURES,
        "input_type": "Structure",
    },
    {
        "id": "picker_biome",
        "label": "Structure",
        "options": BIOMES,
        "input_type": "Biome",
    },
    {
        "id": "picker_poi",
        "label": "Point of Interest",
        "options": POIS,
        "input_type": "Poi",
    },
    {
        "id": "picker_effect",
        "label": "Effect",
        "options": EFFECTS,
        "input_type": "Effect",
    },
    {
        "id": "picker_titleaction",
        "label": "Location",
        "options": TITLEACTIONS,
        "input_type": "TitleAction",
    },
    {
        "id": "picker_metric",
        "label": "Metric",
        "options": METRICS,
        "input_type": "Metric",
    },
    {
        "id": "picker_data_path",
        "label": "Data Path",
        "options": DATA_PATHS,
        "input_type": "DataPath",
    },
]
