import os
import re
from pathlib import Path

# Paths configuration
BASE_DIR = Path("src")
BLOCKS_DIR = BASE_DIR / "blocks"
GENERATORS_DIR = BASE_DIR / "generators/python"

# Files that must be loaded first (if any dependencies exist)
PRIORITY_FILES = ["mc.mjs"]

def find_export_function(file_path):
    """
    Reads a file and returns the name of the exported 'define' function.
    Assumes one main define function per file.
    """
    content = file_path.read_text(encoding='utf-8')
    # Regex to find: export function defineSomething(...)
    match = re.search(r'export\s+function\s+(define\w+)\s*\(', content)
    if match:
        return match.group(1)
    return None

def generate_registry(target_dir, main_function_name, arg_name):
    """
    Scans directory for .mjs files, extracts functions, and writes registry.mjs
    """
    if not target_dir.exists():
        print(f"Directory not found: {target_dir}")
        return

    definitions = []

    # Get all .mjs files excluding the registry itself
    files = [f for f in target_dir.glob("*.mjs") if f.name != "registry.mjs"]

    # Sort files: Priority files first, then alphabetical
    files.sort(key=lambda f: (
        0 if f.name in PRIORITY_FILES else 1,
        f.name
    ))

    for f in files:
        func_name = find_export_function(f)
        if func_name:
            definitions.append({
                "file": f.name,
                "func": func_name
            })
            print(f"  Found {func_name} in {f.name}")

    # Generate the JS content
    lines = ["// Auto-generated registry. Do not edit manually."]
    lines.append(f"// Generated by update_registries.py\n")

    # 1. Imports
    for d in definitions:
        lines.append(f'import {{ {d["func"]} }} from "./{d["file"]}";')

    lines.append("")

    # 2. Main Register Function
    lines.append(f"export function {main_function_name}({arg_name}) {{")
    for d in definitions:
        lines.append(f"    {d['func']}({arg_name});")
    lines.append("}")

    # Write file
    registry_path = target_dir / "registry.mjs"
    registry_path.write_text("\n".join(lines), encoding='utf-8')
    print(f"✅ Generated {registry_path} with {len(definitions)} modules.")

if __name__ == "__main__":
    print("Updating Block Registry...")
    generate_registry(BLOCKS_DIR, "registerAllBlocks", "Blockly")

    print("\nUpdating Generator Registry...")
    generate_registry(GENERATORS_DIR, "registerAllGenerators", "pythonGenerator")