# ========================================== #
#          McJuice Configuration             #
# ========================================== #

# The IP address to bind the McJuice socket server to.
#   "0.0.0.0" -> Listens on all network interfaces (Accessible externally if port is forwarded)
#   "127.0.0.1" -> Listens ONLY on the local machine (Most secure for local development)
host: "0.0.0.0"

# The port that the Python mc-shell environment will connect to.
port: 4721