author: [jeff@thinkae.org]
database: false
description: Implementation of the Minecraft Python API
main: org.mcshell.mcjuice.McJuicePlugin
name: McJuice
startup: postworld
version: '${project.version}'
api-version: '${api.version}'