# AUTO-GENERATED FILE - DO NOT EDIT
class Blocks:
    """Available parameterized blocks and pickers for custom toolboxes."""
    MC_BLOCK_WOOD_PLANKS = {'kind': 'block', 'type': 'mc_block_wood_planks', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_WOOD = {'kind': 'block', 'type': 'mc_block_wood_wood', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_SAPLING = {'kind': 'block', 'type': 'mc_block_wood_sapling', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_LOG = {'kind': 'block', 'type': 'mc_block_wood_log', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_LEAVES = {'kind': 'block', 'type': 'mc_block_wood_leaves', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_COLOR_BED = {'kind': 'block', 'type': 'mc_block_color_bed', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_WOOL = {'kind': 'block', 'type': 'mc_block_color_wool', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_TULIP = {'kind': 'block', 'type': 'mc_block_color_tulip', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_ARMOR_TYPES_BLOCK = {'kind': 'block', 'type': 'mc_block_armor_types_block', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_armor_types_types'}}}}
    MC_BLOCK_WOOD_SHELF = {'kind': 'block', 'type': 'mc_block_wood_shelf', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_STAIRS = {'kind': 'block', 'type': 'mc_block_wood_stairs', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_SIGN = {'kind': 'block', 'type': 'mc_block_wood_sign', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_DOOR = {'kind': 'block', 'type': 'mc_block_wood_door', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_HANGING_SIGN = {'kind': 'block', 'type': 'mc_block_wood_hanging_sign', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_PRESSURE_PLATE = {'kind': 'block', 'type': 'mc_block_wood_pressure_plate', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_FENCE = {'kind': 'block', 'type': 'mc_block_wood_fence', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_COLOR_STAINED_GLASS = {'kind': 'block', 'type': 'mc_block_color_stained_glass', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_WOOD_TRAPDOOR = {'kind': 'block', 'type': 'mc_block_wood_trapdoor', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_COPPER_COPPER_BARS = {'kind': 'block', 'type': 'mc_block_copper_copper_bars', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_CHAIN = {'kind': 'block', 'type': 'mc_block_copper_copper_chain', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_WOOD_FENCE_GATE = {'kind': 'block', 'type': 'mc_block_wood_fence_gate', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_WOOD_BUTTON = {'kind': 'block', 'type': 'mc_block_wood_button', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_COLOR_TERRACOTTA = {'kind': 'block', 'type': 'mc_block_color_terracotta', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_STAINED_GLASS_PANE = {'kind': 'block', 'type': 'mc_block_color_stained_glass_pane', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_CARPET = {'kind': 'block', 'type': 'mc_block_color_carpet', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_BANNER = {'kind': 'block', 'type': 'mc_block_color_banner', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_WOOD_SLAB = {'kind': 'block', 'type': 'mc_block_wood_slab', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_wood_types'}}}}
    MC_BLOCK_COLOR_SHULKER_BOX = {'kind': 'block', 'type': 'mc_block_color_shulker_box', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_GLAZED_TERRACOTTA = {'kind': 'block', 'type': 'mc_block_color_glazed_terracotta', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_CONCRETE = {'kind': 'block', 'type': 'mc_block_color_concrete', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COLOR_CONCRETE_POWDER = {'kind': 'block', 'type': 'mc_block_color_concrete_powder', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COPPER_COPPER_LANTERN = {'kind': 'block', 'type': 'mc_block_copper_copper_lantern', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COLOR_CANDLE = {'kind': 'block', 'type': 'mc_block_color_candle', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_color_types'}}}}
    MC_BLOCK_COPPER_COPPER = {'kind': 'block', 'type': 'mc_block_copper_copper', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_CUT_COPPER = {'kind': 'block', 'type': 'mc_block_copper_cut_copper', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_CHISELED_COPPER = {'kind': 'block', 'type': 'mc_block_copper_chiseled_copper', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_CUT_COPPER_STAIRS = {'kind': 'block', 'type': 'mc_block_copper_cut_copper_stairs', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_CUT_COPPER_SLAB = {'kind': 'block', 'type': 'mc_block_copper_cut_copper_slab', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_DOOR = {'kind': 'block', 'type': 'mc_block_copper_copper_door', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_TRAPDOOR = {'kind': 'block', 'type': 'mc_block_copper_copper_trapdoor', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_GRATE = {'kind': 'block', 'type': 'mc_block_copper_copper_grate', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_BULB = {'kind': 'block', 'type': 'mc_block_copper_copper_bulb', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_CHEST = {'kind': 'block', 'type': 'mc_block_copper_copper_chest', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_COPPER_GOLEM_STATUE = {'kind': 'block', 'type': 'mc_block_copper_copper_golem_statue', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_COPPER_LIGHTNING_ROD = {'kind': 'block', 'type': 'mc_block_copper_lightning_rod', 'inputs': {'VARIANT': {'shadow': {'type': 'picker_copper_types'}}}}
    MC_BLOCK_PICKER_WORLD = {'kind': 'block', 'type': 'mc_block_picker_world'}
    MC_BLOCK_PICKER_MISCELLANEOUS = {'kind': 'block', 'type': 'mc_block_picker_miscellaneous'}
    MC_BLOCK_PICKER_WOODS_AND_LOGS = {'kind': 'block', 'type': 'mc_block_picker_woods_and_logs'}
    MC_BLOCK_PICKER_ORES = {'kind': 'block', 'type': 'mc_block_picker_ores'}
    MC_BLOCK_PICKER_REDSTONE_COMPONENTS = {'kind': 'block', 'type': 'mc_block_picker_redstone_components'}
    MC_BLOCK_PICKER_COLORED_BLOCKS = {'kind': 'block', 'type': 'mc_block_picker_colored_blocks'}
    MC_BLOCK_PICKER_FLOWERS = {'kind': 'block', 'type': 'mc_block_picker_flowers'}
    MC_BLOCK_PICKER_LIGHTING = {'kind': 'block', 'type': 'mc_block_picker_lighting'}
    MC_BLOCK_PICKER_SPAWNING = {'kind': 'block', 'type': 'mc_block_picker_spawning'}
    MC_BLOCK_PICKER_FUNCTIONAL_STORAGE = {'kind': 'block', 'type': 'mc_block_picker_functional_storage'}
    MC_BLOCK_PICKER_NATURE = {'kind': 'block', 'type': 'mc_block_picker_nature'}
    MC_BLOCK_PICKER_MUSIC = {'kind': 'block', 'type': 'mc_block_picker_music'}
    MC_BLOCK_PICKER_GLASS = {'kind': 'block', 'type': 'mc_block_picker_glass'}
    MC_BLOCK_PICKER_BARS = {'kind': 'block', 'type': 'mc_block_picker_bars'}
    MC_BLOCK_PICKER_CHAINS = {'kind': 'block', 'type': 'mc_block_picker_chains'}
    MC_BLOCK_PICKER_WALLS = {'kind': 'block', 'type': 'mc_block_picker_walls'}
    MC_BLOCK_PICKER_COMMANDS = {'kind': 'block', 'type': 'mc_block_picker_commands'}
    MC_BLOCK_PICKER_GLASS_PANE = {'kind': 'block', 'type': 'mc_block_picker_glass_pane'}
    MC_BLOCK_PICKER_PLANTS = {'kind': 'block', 'type': 'mc_block_picker_plants'}
    MC_BLOCK_PICKER_COPPER_VARIANTS = {'kind': 'block', 'type': 'mc_block_picker_copper_variants'}