// Auto-generated registry. Do not edit manually.
// Generated by update_registries.py

import { defineMineCraftBlocks } from "./mc.mjs";
import { defineChatActionsBlocks } from "./ChatActions.mjs";
import { defineDigitalGeometryActionsBlocks } from "./DigitalGeometryActions.mjs";
import { defineDigitalSetActionsBlocks } from "./DigitalSetActions.mjs";
import { defineEventActionsBlocks } from "./EventActions.mjs";
import { defineLSystemShapesBlocks } from "./LSystemShapes.mjs";
import { definePlayerActionsBlocks } from "./PlayerActions.mjs";
import { defineQTurtleActionsBlocks } from "./QTurtleActions.mjs";
import { defineServerActionsBlocks } from "./ServerActions.mjs";
import { defineThreadsBlocks } from "./Threads.mjs";
import { defineTurtleShapesBlocks } from "./TurtleShapes.mjs";
import { defineWorldActionsBlocks } from "./WorldActions.mjs";
import { defineBlocksBlocks } from "./blocks.mjs";
import { defineEntitiesBlocks } from "./entities.mjs";
import { defineItemsBlocks } from "./items.mjs";

export function registerAllBlocks(Blockly) {
    defineMineCraftBlocks(Blockly);
    defineChatActionsBlocks(Blockly);
    defineDigitalGeometryActionsBlocks(Blockly);
    defineDigitalSetActionsBlocks(Blockly);
    defineEventActionsBlocks(Blockly);
    defineLSystemShapesBlocks(Blockly);
    definePlayerActionsBlocks(Blockly);
    defineQTurtleActionsBlocks(Blockly);
    defineServerActionsBlocks(Blockly);
    defineThreadsBlocks(Blockly);
    defineTurtleShapesBlocks(Blockly);
    defineWorldActionsBlocks(Blockly);
    defineBlocksBlocks(Blockly);
    defineEntitiesBlocks(Blockly);
    defineItemsBlocks(Blockly);
}