// Auto-generated registry. Do not edit manually.
// Generated by update_registries.py

import { defineMineCraftBlocks } from "./mc.mjs";
import { defineDigitalGeometryBlocks } from "./DigitalGeometry.mjs";
import { defineEventActionsBlocks } from "./EventActions.mjs";
import { defineLSystemShapesBlocks } from "./LSystemShapes.mjs";
import { definePlayerActionsBlocks } from "./PlayerActions.mjs";
import { definePyncraftActionsBlocks } from "./PyncraftActions.mjs";
import { defineQTurtleActionsBlocks } from "./QTurtleActions.mjs";
import { defineServerActionsBlocks } from "./ServerActions.mjs";
import { defineTurtleShapesBlocks } from "./TurtleShapes.mjs";
import { defineWorldActionsBlocks } from "./WorldActions.mjs";
import { defineMineCraftEntityBlocks } from "./entities.mjs";
import { defineMineCraftMaterialBlocks } from "./materials.mjs";

export function registerAllBlocks(Blockly) {
    defineMineCraftBlocks(Blockly);
    defineDigitalGeometryBlocks(Blockly);
    defineEventActionsBlocks(Blockly);
    defineLSystemShapesBlocks(Blockly);
    definePlayerActionsBlocks(Blockly);
    definePyncraftActionsBlocks(Blockly);
    defineQTurtleActionsBlocks(Blockly);
    defineServerActionsBlocks(Blockly);
    defineTurtleShapesBlocks(Blockly);
    defineWorldActionsBlocks(Blockly);
    defineMineCraftEntityBlocks(Blockly);
    defineMineCraftMaterialBlocks(Blockly);
}