import {MCED} from "../../lib/constants.mjs";
import {ACTION_CLASSES} from "./action_classes.mjs"; // Auto-generated by build.py

export function defineMineCraftGenerators(pythonGenerator) {
    // Set the standard Python indent to 4 spaces
    pythonGenerator.INDENT = '    ';

    // Flag for simplified UI preview
    pythonGenerator.isSchematic = false;

    /**
     * Initializes the generator by clearing the custom methods cache.
     * This ensures that deleted powers do not persist in the generated code.
     */
    const previousInit = pythonGenerator.init;
    pythonGenerator.init = function (workspace) {
        if (previousInit) {
            previousInit.call(this, workspace);
        }
        // Issue #2 Fix: Clear methods cache to prevent stale code
        pythonGenerator.methods_ = {};
        // Reset the flag that tracks if any thread blocks were used
        pythonGenerator.hasThreads = false;
    };

    /**
     * The 'finish' method acts as the compiler for the mc-shell environment.
     * It maps generic namespaces to the specific execution context.
     */
    pythonGenerator.finish = function (code) {
        const classIndent = this.INDENT || '    ';

        // Dynamically imported directly from the active build pipeline!
        let actionClasses = ACTION_CLASSES;

        // Helper function to process both main code and generated definitions
        const processText = (text) => {
            if (pythonGenerator.isSchematic) {
                // Add 'mc.' namespace for the simple view
                actionClasses.forEach(className => {
                    // Catch the active runnable prefix
                    const reImpl = new RegExp(`self\\.action_implementer\\.${className}\\.`, 'g');
                    text = text.replace(reImpl, 'mc.');

                    // Catch the raw ClassName. in case it hasn't been replaced yet
                    const reRaw = new RegExp(`\\b${className}\\.`, 'g');
                    text = text.replace(reRaw, 'mc.');
                });
                // Final schematic fallback replacements
                text = text.replace(/self\.action_implementer\./g, 'mc.');
            } else {
                // Correctly replace ClassName.method(...) with self.action_implementer.method(...)
                actionClasses.forEach(className => {
                    const re = new RegExp(`\\b${className}\\.`, 'g');
                    text = text.replace(re, 'self.action_implementer.');
                });
            }
            return text;
        };

        // 1. Process the main execution code
        code = processText(code);

        // 2. Process all custom procedures, loops, and threads
        const definitions = Object.values(this.methods_ || {});

        // Format definitions with proper indentation and replacements
        const classLevelDefinitions = definitions.map(def => {
            let processedDef = processText(def);
            return processedDef.split('\n').map(line => line ? classIndent + line : line).join('\n');
        });

        const imports = [
            'import threading',
            'import time',
            'from mcshell.constants import *',
            'from mcshell.mcplayer import PowerCancelledException'
        ].join('\n');

        const header = `\n# Generated by Blockly MC-ED\n\nclass BlocklyProgramRunner:\n${classIndent}def __init__(self, action_implementer_instance, cancel_event=None, runtime_params={}):\n${classIndent}${classIndent}self.action_implementer = action_implementer_instance\n${classIndent}${classIndent}self.cancel_event = cancel_event\n${classIndent}${classIndent}self.runtime_params = runtime_params\n${classIndent}${classIndent}self.active_threads = []\n`;

        const injectedCode = code.split('\n')
            .map(line => line ? classIndent + classIndent + line : line)
            .join('\n');

        // Optional Thread Lifecycle hook
        let infiniteLoop = "";
        if (pythonGenerator.hasThreads && !pythonGenerator.isSchematic) {
            infiniteLoop = `\n${classIndent}${classIndent}# Infinite loop to keep the main thread alive for active background events\n${classIndent}${classIndent}while True:\n${classIndent}${classIndent}${classIndent}if self.cancel_event and self.cancel_event.is_set():\n${classIndent}${classIndent}${classIndent}${classIndent}break\n${classIndent}${classIndent}${classIndent}time.sleep(0.1)\n`;
        }

        let runMethod = `\n${classIndent}def run_program(self):\n${classIndent}${classIndent}if self.cancel_event and self.cancel_event.is_set(): return\n${injectedCode}${infiniteLoop}`;

        if (pythonGenerator.isSchematic) {
            let schematicDefs = definitions.map(processText);
            return code + '\n\n' + schematicDefs.join('\n\n');
        }

        return imports + '\n' + header + '\n' + classLevelDefinitions.join('\n\n') + '\n\n' + runMethod;
    };

   // --- LOOP GENERATORS (Fixed to avoid upRange/downRange helpers) ---

    const CANCELLATION_CHECK_LOOP = 'if self.cancel_event and self.cancel_event.is_set(): break\ntime.sleep(0)\n';
    const CANCELLATION_CHECK_FUNCTION = 'if self.cancel_event and self.cancel_event.is_set(): return\n';

    pythonGenerator.forBlock['controls_repeat_ext'] = function (block, generator) {
        const times = generator.valueToCode(block, 'TIMES', generator.ORDER_NONE) || '0';
        let branch = generator.statementToCode(block, 'DO');
        const loopVar = generator.nameDB_.getDistinctName('count', MCED.BlocklyNameTypes.VARIABLE);

        // Hide cancel check in schematic view
        const check = generator.isSchematic ? '' : generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT);
        return `for ${loopVar} in range(int(${times})):\n${check}${branch}`;
    };

    pythonGenerator.forBlock['controls_whileUntil'] = function (block, generator) {
        const until = block.getFieldValue('MODE') === 'UNTIL';
        var argument0 = generator.valueToCode(block, 'BOOL', until ? generator.ORDER_LOGICAL_NOT : generator.ORDER_NONE) || 'False';
        let branch = generator.statementToCode(block, 'DO');

        const check = generator.isSchematic ? '' : generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT);
        branch = `${check}${branch}`;
        if (until) { argument0 = 'not ' + argument0; }
        return 'while ' + argument0 + ':\n' + branch;
    };

    pythonGenerator.forBlock['controls_for'] = function (block, generator) {
        const variable0 = generator.nameDB_.getName(block.getFieldValue('VAR'), MCED.BlocklyNameTypes.VARIABLE);
        const fromVal = generator.valueToCode(block, 'FROM', generator.ORDER_NONE) || '0';
        const toVal = generator.valueToCode(block, 'TO', generator.ORDER_NONE) || '0';
        const byVal = generator.valueToCode(block, 'BY', generator.ORDER_NONE) || '1';
        let branch = generator.statementToCode(block, 'DO') || generator.INDENT + 'pass\n';

        const check = generator.isSchematic ? '' : generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT);
        branch = `${check}${branch}`;

        // Uses a robust range() call to handle inclusive boundaries without helper functions
        const rangeCode = `range(int(${fromVal}), int(${toVal}) + (1 if int(${fromVal}) <= int(${toVal}) else -1), int(${byVal}))`;
        return `for ${variable0} in ${rangeCode}:\n${branch}`;
    };

    pythonGenerator.forBlock['controls_forEach'] = function (block, generator) {
        const variable0 = generator.nameDB_.getName(block.getFieldValue('VAR'), MCED.BlocklyNameTypes.VARIABLE);
        const list = generator.valueToCode(block, 'LIST', generator.ORDER_NONE) || '[]';
        let branch = generator.statementToCode(block, 'DO') || generator.INDENT + 'pass\n';

        const check = generator.isSchematic ? '' : generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT);
        branch = `${check}${branch}`;

        return `for ${variable0} in ${list}:\n${branch}`;
    };

    // --- PROCEDURE GENERATORS ---

    pythonGenerator.forBlock['procedures_defnoreturn'] = function (block, generator) {
        const funcName = generator.nameDB_.getName(block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        let branch = generator.statementToCode(block, 'STACK') || (generator.INDENT + 'pass\n');

        const check = generator.isSchematic ? '' : generator.prefixLines(CANCELLATION_CHECK_FUNCTION, generator.INDENT);
        branch = `${check}${branch}`;

        const args = block.getVars().map(v => generator.nameDB_.getName(v, MCED.BlocklyNameTypes.VARIABLE));
        // Note: Defined with 'self' internally; finish() cleans it for schematic display
        let code = `def ${funcName}(self, ${args.join(', ')}):\n${branch}`;

        if (!generator.methods_) generator.methods_ = {};
        generator.methods_['%' + funcName] = code;
        return null;
    };

    pythonGenerator.forBlock['procedures_defreturn'] = function (block, generator) {
        const funcName = generator.nameDB_.getName(block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        let branch = generator.statementToCode(block, 'STACK');
        let returnValue = generator.valueToCode(block, 'RETURN', generator.ORDER_NONE) || 'None';
        const returnStatement = generator.INDENT + 'return ' + returnValue + '\n';

        const check = generator.isSchematic ? '' : generator.prefixLines(CANCELLATION_CHECK_FUNCTION, generator.INDENT);
        branch = `${check}${branch || ''}${returnStatement}`;

        const args = block.getVars().map(v => generator.nameDB_.getName(v, MCED.BlocklyNameTypes.VARIABLE));
        let code = `def ${funcName}(self, ${args.join(', ')}):\n${branch}`;

        if (!generator.methods_) generator.methods_ = {};
        generator.methods_['%' + funcName] = code;
        return null;
    };

    pythonGenerator.forBlock['procedures_callnoreturn'] = function (block, generator) {
        const funcName = generator.nameDB_.getName(block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        const argNames = block.getVars();
        const args = argNames.map((name, i) => {
            const varName = generator.nameDB_.getName(name, MCED.BlocklyNameTypes.VARIABLE);
            const val = generator.valueToCode(block, 'ARG' + i, generator.ORDER_NONE) || `self.runtime_params.get('${varName}', None)`;
            return `${varName}=${val}`;
        });
        return `self.${funcName}(${args.join(', ')})\n`;
    };

    pythonGenerator.forBlock['procedures_callreturn'] = function (block, generator) {
        const funcName = generator.nameDB_.getName(block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        const argNames = block.getVars();
        const args = argNames.map((name, i) => {
            const varName = generator.nameDB_.getName(name, MCED.BlocklyNameTypes.VARIABLE);
            const val = generator.valueToCode(block, 'ARG' + i, generator.ORDER_NONE) || `self.runtime_params.get('${varName}', None)`;
            return `${varName}=${val}`;
        });
        const code = `self.${funcName}(${args.join(', ')})`;
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['procedures_ifreturn'] = function (block, generator) {
        const condition = generator.valueToCode(block, 'CONDITION', generator.ORDER_NONE) || 'False';
        let code = 'if ' + condition + ':\n';
        if (block.hasReturnValue_) {
            const value = generator.valueToCode(block, 'VALUE', generator.ORDER_NONE) || 'None';
            code += generator.INDENT + 'return ' + value + '\n';
        } else {
            code += generator.INDENT + 'return\n';
        }
        return code;
    };

    // --- MATH & MINECRAFT DATA STRUCTURES ---

    pythonGenerator.forBlock['minecraft_matrix_3d_elements'] = function (block, generator) {
        const r00 = generator.valueToCode(block, 'R00', generator.ORDER_ATOMIC) || '1.0';
        const r01 = generator.valueToCode(block, 'R01', generator.ORDER_ATOMIC) || '0.0';
        const r02 = generator.valueToCode(block, 'R02', generator.ORDER_ATOMIC) || '0.0';
        const r10 = generator.valueToCode(block, 'R10', generator.ORDER_ATOMIC) || '0.0';
        const r11 = generator.valueToCode(block, 'R11', generator.ORDER_ATOMIC) || '1.0';
        const r12 = generator.valueToCode(block, 'R12', generator.ORDER_ATOMIC) || '0.0';
        const r20 = generator.valueToCode(block, 'R20', generator.ORDER_ATOMIC) || '0.0';
        const r21 = generator.valueToCode(block, 'R21', generator.ORDER_ATOMIC) || '0.0';
        const r22 = generator.valueToCode(block, 'R22', generator.ORDER_ATOMIC) || '1.0';

        const code = `Matrix3([[${r00}, ${r01}, ${r02}], [${r10}, ${r11}, ${r12}], [${r20}, ${r21}, ${r22}]])`;
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_matrix_3d_euler'] = function (block, generator) {
        const yaw = generator.valueToCode(block, 'YAW', generator.ORDER_ATOMIC) || '0.0';
        const pitch = generator.valueToCode(block, 'PITCH', generator.ORDER_ATOMIC) || '0.0';
        const roll = generator.valueToCode(block, 'ROLL', generator.ORDER_ATOMIC) || '0.0';

        const code = `Matrix3.from_euler_angles(yaw_degrees=${yaw}, pitch_degrees=${pitch}, roll_degrees=${roll})`;
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_vector_3d'] = function (block, generator) {
        const x = generator.valueToCode(block, 'X', generator.ORDER_ATOMIC) || '0';
        const y = generator.valueToCode(block, 'Y', generator.ORDER_ATOMIC) || '0';
        const z = generator.valueToCode(block, 'Z', generator.ORDER_ATOMIC) || '0';
        return [`Vec3(${x}, ${y}, ${z})`, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_vector_get_attribute'] = function (block, generator) {
        const vector = generator.valueToCode(block, 'VECTOR', generator.ORDER_ATOMIC) || 'Vec3(0, 0, 0)';
        const component = block.getFieldValue('COMPONENT').toLowerCase();
        return [`${vector}.${component}`, generator.ORDER_MEMBER];
    };

    pythonGenerator.forBlock['minecraft_vector_delta'] = function (block, generator) {
        const xValue = block.getFieldValue('X');
        const yValue = block.getFieldValue('Y');
        const zValue = block.getFieldValue('Z');
        return [`Vec3(${xValue},${yValue},${zValue})`, generator.ORDER_ATOMIC];
    }

    pythonGenerator.forBlock['minecraft_vector_binary_op'] = function (block, generator) {
        const OPERATORS = {
            'ADD': [' + ', generator.ORDER_ADDITIVE],
            'SUBTRACT': [' - ', generator.ORDER_ADDITIVE],
            'CROSS': ['.cross(', generator.ORDER_FUNCTION_CALL],
        };
        const op = block.getFieldValue('OP');
        const tuple = OPERATORS[op];
        const vectorA = generator.valueToCode(block, 'A', tuple[1]) || 'Vec3()';
        const vectorB = generator.valueToCode(block, 'B', tuple[1]) || 'Vec3()';

        let code = op === 'CROSS' ? `${vectorA}${tuple[0]}${vectorB})` : `${vectorA}${tuple[0]}${vectorB}`;
        return [code, tuple[1]];
    };

    pythonGenerator.forBlock['minecraft_vector_scalar_multiply'] = function (block, generator) {
        const vector = generator.valueToCode(block, 'A', generator.ORDER_MULTIPLICATIVE) || 'Vec3()';
        const scalar = generator.valueToCode(block, 'B', generator.ORDER_MULTIPLICATIVE) || '1';
        return [`${vector} * ${scalar}`, generator.ORDER_MULTIPLICATIVE];
    };

    pythonGenerator.forBlock['minecraft_vector_dot_product'] = function (block, generator) {
        const vectorA = generator.valueToCode(block, 'A', generator.ORDER_ATOMIC) || 'Vec3()';
        const vectorB = generator.valueToCode(block, 'B', generator.ORDER_ATOMIC) || 'Vec3()';
        return [`${vectorA}.dot(${vectorB})`, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_matrix_vector_multiply'] = function (block, generator) {
        const matrix = generator.valueToCode(block, 'A', generator.ORDER_MULTIPLICATIVE) || 'Matrix3.identity()';
        const vector = generator.valueToCode(block, 'B', generator.ORDER_MULTIPLICATIVE) || 'Vec3()';
        return [`${matrix} @ ${vector}`, generator.ORDER_MULTIPLICATIVE];
    };

    // --- PLAYER & POSITION GENERATORS ---

    pythonGenerator.forBlock['minecraft_position_get_direction'] = function (block, generator) {
        return [`self.action_implementer.mcplayer.direction`, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['minecraft_position_player'] = function (block, generator) {
        return [`self.action_implementer.mcplayer.position`, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['minecraft_position_player_tile'] = function (block, generator) {
        return [`self.action_implementer.mcplayer.tile_position`, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['minecraft_position_here'] = function (block, generator) {
        return [`self.action_implementer.mcplayer.here`, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['minecraft_position_get_compass_direction'] = function (block, generator) {
        return ['self.action_implementer.mcplayer.compass_direction', generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_coloured_block_picker'] = function (block, generator) {
        const colourId = block.getFieldValue('MINECRAFT_COLOUR_ID');
        return [`'${colourId}'`, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['time_sleep'] = function (block, generator) {
        const seconds = generator.valueToCode(block, 'SECONDS', generator.ORDER_ATOMIC) || '1';
        return `time.sleep(${seconds})\n`;
    };
}