import {MCED} from "../../lib/constants.mjs";

export function defineMineCraftGenerators(pythonGenerator) {
    // Set the standard Python indent to 4 spaces
    pythonGenerator.INDENT = '    ';

     /**
     * Initializes the generator by clearing the custom methods cache.
     * This is called by Blockly before code generation begins.
     */

    // 1. Store the original init function from the pythonGenerator prototype.
    const originalInit = pythonGenerator.init;

    // 2. Create a new init function that calls the original and adds our logic.
    pythonGenerator.init = function(workspace) {
        // First, call the original init function. This is CRUCIAL.
        // It sets up core features like the name database (nameDB_).
        originalInit.call(this, workspace);

        // Now, add our custom initialization for tracking user-defined methods.
        // We can be sure that 'this' refers to the generator instance.
        this.methods_ = Object.create(null);
    };

    /**
     * Finalize the code by wrapping it in the BlocklyProgramRunner class,
     * prepending any user-defined methods.
     */

    pythonGenerator.finish = function(code) {
        // 'code' is the main execution flow for the run_program() method.

        const definitions = Object.values(pythonGenerator.methods_ || {});
        const classIndent = pythonGenerator.INDENT;
        const userDefinedMethods = definitions.length > 0 ?
            '\n' + definitions
                .map(methodDef => pythonGenerator.prefixLines(methodDef, classIndent))
                .join('\n\n')
            : '';

        const methodBodyIndent = classIndent + classIndent;
        const indentedBlockCode = pythonGenerator.prefixLines(code, methodBodyIndent) || (methodBodyIndent + 'pass');

        // --- The final script template ---
        const imports = 'from mcshell.constants import *\n';
        const now = new Date();
        const timestamp = now.toISOString();

        const finalScript = `
    ${imports}
# Generated by Blockly MC-ED on ${timestamp}

class BlocklyProgramRunner:
    def __init__(self, action_implementer_instance, cancel_event=None, runtime_params={}):
        self.action_implementer = action_implementer_instance
        self.cancel_event = cancel_event
        self.runtime_params = runtime_params
${userDefinedMethods}

    def run_program(self):
        if self.cancel_event and self.cancel_event.is_set(): return
${indentedBlockCode}
`;
        return finalScript.trim() + '\n';
    };

    // --- Generators with Cancellation Checks ---

    const CANCELLATION_CHECK_LOOP = 'if self.cancel_event and self.cancel_event.is_set(): break\neventlet.sleep(0)\n';
    const CANCELLATION_CHECK_FUNCTION = 'if self.cancel_event and self.cancel_event.is_set(): return\n';

    // -- Loops --
    pythonGenerator.forBlock['controls_repeat_ext'] = function(block, generator) {
        const times = generator.valueToCode(block, 'TIMES', generator.ORDER_NONE) || '0';
        let branch = generator.statementToCode(block, 'DO');
        const loopVar = generator.nameDB_.getDistinctName('count', MCED.BlocklyNameTypes.VARIABLE);
        const code = `for ${loopVar} in range(int(${times})):\n${generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT)}${branch}`;
        return code;
    };

    pythonGenerator.forBlock['controls_whileUntil'] = function(block, generator) {
        const until = block.getFieldValue('MODE') === 'UNTIL';
        var argument0 = generator.valueToCode(block, 'BOOL', until ? generator.ORDER_LOGICAL_NOT : generator.ORDER_NONE) || 'False';
        let branch = generator.statementToCode(block, 'DO');
        branch = `${generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT)}${branch}`;
        if (until) {
            argument0 = 'not ' + argument0;
        }
        return 'while ' + argument0 + ':\n' + branch;
    };

   pythonGenerator.forBlock['controls_for'] = function(block, generator) {
        const variable0 = generator.nameDB_.getName(
            block.getFieldValue('VAR'),
            MCED.BlocklyNameTypes.VARIABLE
        );
        const fromVal = generator.valueToCode(block, 'FROM', generator.ORDER_NONE) || '0';
        const toVal = generator.valueToCode(block, 'TO', generator.ORDER_NONE) || '0';
        const byVal = generator.valueToCode(block, 'BY', generator.ORDER_NONE) || '1';

        let branch = generator.statementToCode(block, 'DO') || generator.INDENT + 'pass\n';

        // Correctly add the cancellation check to the top of the loop body
        const cancelCheck = generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT);
        branch = `${cancelCheck}${branch}`;

        // Helper function to create a robust range
        const rangeCode = `range(int(${fromVal}), int(${toVal}) + (1 if int(${fromVal}) <= int(${toVal}) else -1), int(${byVal}))`;

        const code = `for ${variable0} in ${rangeCode}:\n${branch}`;
        return code;
    };

    pythonGenerator.forBlock['controls_forEach'] = function(block, generator) {
        const variable0 = generator.nameDB_.getName(
            block.getFieldValue('VAR'),
            MCED.BlocklyNameTypes.VARIABLE
        );
        const list = generator.valueToCode(block, 'LIST', generator.ORDER_NONE) || '[]';

        let branch = generator.statementToCode(block, 'DO') || generator.INDENT + 'pass\n';

        // Correctly add the cancellation check to the top of the loop body
        const cancelCheck = generator.prefixLines(CANCELLATION_CHECK_LOOP, generator.INDENT);
        branch = `${cancelCheck}${branch}`;

        const code = `for ${variable0} in ${list}:\n${branch}`;
        return code;
    };

    // -- Functions --
    pythonGenerator.forBlock['procedures_defnoreturn'] = function(block, generator) {
        const funcName = generator.nameDB_.getName(block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        let branch = generator.statementToCode(block, 'STACK') || (generator.INDENT + 'pass\n');
        branch = `${generator.prefixLines(CANCELLATION_CHECK_FUNCTION, generator.INDENT)}${branch}`; // Prepend check
        const args = block.getVars().map(v => generator.nameDB_.getName(v, MCED.BlocklyNameTypes.VARIABLE));
        let code = `def ${funcName}(self, ${args.join(', ')}):\n${branch}`;
        if (!generator.methods_) generator.methods_ = {};
        generator.methods_['%' + funcName] = code;
        return null;
    };

    pythonGenerator.forBlock['procedures_defreturn'] = function(block, generator) {
        const funcName = generator.nameDB_.getName(block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        let branch = generator.statementToCode(block, 'STACK');
        let returnValue = generator.valueToCode(block, 'RETURN', generator.ORDER_NONE) || 'None';
        const returnStatement = generator.INDENT + 'return ' + returnValue + '\n';
        branch = (branch || '') + returnStatement;
        branch = `${generator.prefixLines(CANCELLATION_CHECK_FUNCTION, generator.INDENT)}${branch}`; // Prepend check
        const args = block.getVars().map(v => generator.nameDB_.getName(v, MCED.BlocklyNameTypes.VARIABLE));
        let code = `def ${funcName}(self, ${args.join(', ')}):\n${branch}`;
        if (!generator.methods_) generator.methods_ = {};
        generator.methods_['%' + funcName] = code;
        return null;
    };

    // --- Generators for Function Definition and Call Blocks ---

    pythonGenerator.forBlock['procedures_callnoreturn'] = function(block, generator) {
        const funcName = generator.nameDB_.getName(
            block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);

        const argNames = block.getVars(); // The names of the function's parameters, e.g., ['height', 'material']
        const args = [];

        // For each argument the function expects...
        for (let i = 0; i < argNames.length; i++) {
            const varName = generator.nameDB_.getName(argNames[i], MCED.BlocklyNameTypes.VARIABLE);

            // Check if a block is connected to this argument's input socket
            const connectedBlock = block.getInputTargetBlock('ARG' + i);

            let argCode;
            if (connectedBlock) {
                // --- Case 1: A block is connected (Editor Debugging) ---
                // Generate the code for the connected block directly.
                argCode = generator.valueToCode(block, 'ARG' + i, generator.ORDER_NONE) || 'None';
            } else {
                // --- Case 2: The input is empty (Control UI Execution) ---
                // Generate code to look up the parameter from the runtime dictionary.
                argCode = `self.runtime_params.get('${varName}', None)`;
            }

            // Add it to the list as a keyword argument
            args.push(`${varName}=${argCode}`);
        }

        const code = 'self.' + funcName + '(' + args.join(', ') + ')\n';
        return code;
    };

    pythonGenerator.forBlock['procedures_callreturn'] = function(block, generator) {
        const funcName = generator.nameDB_.getName(
            block.getFieldValue('NAME'), MCED.BlocklyNameTypes.PROCEDURE);
        const argNames = block.getVars();
        const args = [];
        for (let i = 0; i < argNames.length; i++) {
            const varName = generator.nameDB_.getName(argNames[i], MCED.BlocklyNameTypes.VARIABLE);
            const connectedBlock = block.getInputTargetBlock('ARG' + i);
            let argCode = connectedBlock
                ? (generator.valueToCode(block, 'ARG' + i, generator.ORDER_NONE) || 'None')
                : `self.runtime_params.get('${varName}', None)`;
            args.push(`${varName}=${argCode}`);
        }
        const code = 'self.' + funcName + '(' + args.join(', ') + ')';
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['procedures_ifreturn'] = function(block, generator) {
        // Conditionally return a value from a procedure.
        const condition = generator.valueToCode(block, 'CONDITION', generator.ORDER_NONE) || 'False';
        let code = 'if ' + condition + ':\n';
        if (block.hasReturnValue_) {
            const value = generator.valueToCode(block, 'VALUE', generator.ORDER_NONE) || 'None';
            code += generator.INDENT + 'return ' + value + '\n';
        } else {
            code += generator.INDENT + 'return\n';
        }
        return code;
    };

    pythonGenerator.forBlock['minecraft_matrix_3d_elements'] = function(block, generator) {
        const r00 = generator.valueToCode(block, 'R00', generator.ORDER_ATOMIC) || '1.0';
        const r01 = generator.valueToCode(block, 'R01', generator.ORDER_ATOMIC) || '0.0';
        const r02 = generator.valueToCode(block, 'R02', generator.ORDER_ATOMIC) || '0.0';
        const r10 = generator.valueToCode(block, 'R10', generator.ORDER_ATOMIC) || '0.0';
        const r11 = generator.valueToCode(block, 'R11', generator.ORDER_ATOMIC) || '1.0';
        const r12 = generator.valueToCode(block, 'R12', generator.ORDER_ATOMIC) || '0.0';
        const r20 = generator.valueToCode(block, 'R20', generator.ORDER_ATOMIC) || '0.0';
        const r21 = generator.valueToCode(block, 'R21', generator.ORDER_ATOMIC) || '0.0';
        const r22 = generator.valueToCode(block, 'R22', generator.ORDER_ATOMIC) || '1.0';

        const code = `Matrix3([[${r00}, ${r01}, ${r02}], [${r10}, ${r11}, ${r12}], [${r20}, ${r21}, ${r22}]])`;
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_matrix_3d_euler'] = function(block, generator) {
        const yaw = generator.valueToCode(block, 'YAW', generator.ORDER_ATOMIC) || '0.0';
        const pitch = generator.valueToCode(block, 'PITCH', generator.ORDER_ATOMIC) || '0.0';
        const roll = generator.valueToCode(block, 'ROLL', generator.ORDER_ATOMIC) || '0.0';

        const code = `Matrix3.from_euler_angles(yaw_degrees=${yaw}, pitch_degrees=${pitch}, roll_degrees=${roll})`;
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['vector_3d_shadow'] = function(block, generator) {
        const x = generator.valueToCode(block, 'X', generator.ORDER_ATOMIC) || '0';
        const y = generator.valueToCode(block, 'Y', generator.ORDER_ATOMIC) || '0';
        const z = generator.valueToCode(block, 'Z', generator.ORDER_ATOMIC) || '0';
        const code = `Vec3(${x}, ${y}, ${z})`;
        return [code, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['minecraft_vector_3d'] = function(block, generator) {
        // Use valueToCode for each input, providing a default value of '0' if nothing is connected.
        const x = generator.valueToCode(block, 'X', generator.ORDER_ATOMIC) || '0';
        const y = generator.valueToCode(block, 'Y', generator.ORDER_ATOMIC) || '0';
        const z = generator.valueToCode(block, 'Z', generator.ORDER_ATOMIC) || '0';

        // The code instantiates the Vec3 class with the code from the inputs.
        const code = `Vec3(${x}, ${y}, ${z})`;

        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_vector_get_attribute'] = function(block, generator) {
        const vector = generator.valueToCode(block, 'VECTOR', generator.ORDER_ATOMIC) || 'Vec3(0, 0, 0)';
        const component = block.getFieldValue('COMPONENT').toLowerCase();

        const code = `${vector}.${component}`;

        return [code, generator.ORDER_MEMBER];
    };

    pythonGenerator.forBlock['minecraft_vector_delta'] = function (block,generator) {
        const xValue = block.getFieldValue('X');
        const yValue = block.getFieldValue('Y');
        const zValue = block.getFieldValue('Z');

        let code = `Vec3(${xValue},${yValue},${zValue})`
        return [code,generator.ORDER_ATOMIC];
    }

    pythonGenerator.forBlock['minecraft_position_get_direction'] = function (block,generator) {
        let code = `self.action_implementer.mcplayer.direction`
        return [code,generator.ORDER_ATOMIC];
    }

    pythonGenerator.forBlock['minecraft_position_player'] = function (block,generator) {
        let code = `self.action_implementer.mcplayer.position`
        return [code,generator.ORDER_ATOMIC];
    }

    pythonGenerator.forBlock['minecraft_position_player_tile'] = function (block,generator) {
        let code = `self.action_implementer.mcplayer.tile_position`
        return [code,generator.ORDER_ATOMIC];
    }

    pythonGenerator.forBlock['minecraft_position_here'] = function (block,generator) {
        let code = `self.action_implementer.mcplayer.here`
        return [code,generator.ORDER_ATOMIC];
    }

    pythonGenerator.forBlock['minecraft_position_get_compass_direction'] = function(block, generator) {
        // This generates a call to a method that returns the direction string.
        const code = 'self.action_implementer.mcplayer.compass_direction';

        // Return the code and the order of operations for a function call.
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_vector_binary_op'] = function(block, generator) {
        const OPERATORS = {
            'ADD': [' + ', generator.ORDER_ADDITIVE],
            'SUBTRACT': [' - ', generator.ORDER_ADDITIVE],
            'CROSS': ['.cross(', generator.ORDER_FUNCTION_CALL],
        };
        const op = block.getFieldValue('OP');
        const tuple = OPERATORS[op];
        const operatorString = tuple[0];
        const order = tuple[1];

        const vectorA = generator.valueToCode(block, 'A', order) || 'Vec3()';
        const vectorB = generator.valueToCode(block, 'B', order) || 'Vec3()';

        let code;
        if (op === 'CROSS') {
            code = `${vectorA}${operatorString}${vectorB})`;
        } else {
            code = `${vectorA}${operatorString}${vectorB}`;
        }

        return [code, order];
    };

    pythonGenerator.forBlock['minecraft_vector_scalar_multiply'] = function(block, generator) {
        const vector = generator.valueToCode(block, 'A', generator.ORDER_MULTIPLICATIVE) || 'Vec3()';
        const scalar = generator.valueToCode(block, 'B', generator.ORDER_MULTIPLICATIVE) || '1';
        const code = `${vector} * ${scalar}`;
        return [code, generator.ORDER_MULTIPLICATIVE];
    };

    pythonGenerator.forBlock['minecraft_vector_dot_product'] = function(block, generator) {
        const vectorA = generator.valueToCode(block, 'A', generator.ORDER_ATOMIC) || 'Vec3()';
        const vectorB = generator.valueToCode(block, 'B', generator.ORDER_ATOMIC) || 'Vec3()';
        const code = `${vectorA}.dot(${vectorB})`;
        return [code, generator.ORDER_FUNCTION_CALL];
    };

    pythonGenerator.forBlock['minecraft_matrix_vector_multiply'] = function(block, generator) {
        const matrix = generator.valueToCode(block, 'A', generator.ORDER_MULTIPLICATIVE) || 'Matrix3.identity()';
        const vector = generator.valueToCode(block, 'B', generator.ORDER_MULTIPLICATIVE) || 'Vec3()';
        const code = `${matrix} @ ${vector}`; // Use the @ operator for matrix multiplication
        return [code, generator.ORDER_MULTIPLICATIVE];
    };

    pythonGenerator.forBlock['minecraft_coloured_block_picker'] = function(block, generator) {
      const colourId = block.getFieldValue('MINECRAFT_COLOUR_ID'); // e.g., "WHITE", "RED"
      return [`'${colourId}'`, generator.ORDER_ATOMIC];
    };

    pythonGenerator.forBlock['time_sleep'] = function(block, generator) {
        const seconds = generator.valueToCode(block, 'SECONDS', generator.ORDER_ATOMIC) || '1';

        const code = `time.sleep(${seconds})\n`;
        return code;
    };

}