// Auto-generated registry. Do not edit manually.
// Generated by update_registries.py

import { defineMineCraftGenerators } from "./mc.mjs";
import { defineDigitalGeometryGenerators } from "./DigitalGeometry.mjs";
import { defineDigitalGeometryActionsGenerators } from "./DigitalGeometryActions.mjs";
import { defineEventActionsGenerators } from "./EventActions.mjs";
import { defineLSystemShapesGenerators } from "./LSystemShapes.mjs";
import { definePlayerActionsGenerators } from "./PlayerActions.mjs";
import { definePyncraftActionsGenerators } from "./PyncraftActions.mjs";
import { defineQTurtleActionsGenerators } from "./QTurtleActions.mjs";
import { defineServerActionsGenerators } from "./ServerActions.mjs";
import { defineThreadsGenerators } from "./Threads.mjs";
import { defineTurtleShapesGenerators } from "./TurtleShapes.mjs";
import { defineWorldActionsGenerators } from "./WorldActions.mjs";
import { defineBlocksGenerators } from "./blocks.mjs";
import { defineEntitiesGenerators } from "./entities.mjs";
import { defineItemsGenerators } from "./items.mjs";
import { defineMaterialsGenerators } from "./materials.mjs";

export function registerAllGenerators(pythonGenerator) {
    defineMineCraftGenerators(pythonGenerator);
    defineDigitalGeometryGenerators(pythonGenerator);
    defineDigitalGeometryActionsGenerators(pythonGenerator);
    defineEventActionsGenerators(pythonGenerator);
    defineLSystemShapesGenerators(pythonGenerator);
    definePlayerActionsGenerators(pythonGenerator);
    definePyncraftActionsGenerators(pythonGenerator);
    defineQTurtleActionsGenerators(pythonGenerator);
    defineServerActionsGenerators(pythonGenerator);
    defineThreadsGenerators(pythonGenerator);
    defineTurtleShapesGenerators(pythonGenerator);
    defineWorldActionsGenerators(pythonGenerator);
    defineBlocksGenerators(pythonGenerator);
    defineEntitiesGenerators(pythonGenerator);
    defineItemsGenerators(pythonGenerator);
    defineMaterialsGenerators(pythonGenerator);
}