from mcshell.mcactions_base import MCActionsBase
from blockapily import mced_block
from mcshell.Vec3 import Vec3
from typing import Optional, Any

# --- THIS FILE IS AUTOMATICALLY GENERATED FROM mcjuice_api.yaml ---
# --- Do not edit directly! Inherit from these classes instead. ---


class GeneratedPlayerActions(MCActionsBase):
    def __init__(self, mc_player_instance, delay_between_blocks=0):
        super().__init__(mc_player_instance, delay_between_blocks)

    @mced_block(
        label="Get Position"
    )
    def get_pos(self) -> 'Vec3':
        """Gets the exact XYZ position of the player."""
        return self.mcplayer.mj.player.getPos()

    @mced_block(
        label="Set Position to [pos]",
        pos={'label': 'Position'}
    )
    def set_pos(self, pos: 'Vec3'):
        self.mcplayer.mj.player.setPos(float(pos.x), float(pos.y), float(pos.z))

    @mced_block(
        label="Get Tile Position"
    )
    def get_tile_pos(self) -> 'Vec3':
        """Gets the integer block position of the player."""
        return self.mcplayer.mj.player.getTilePos()

    @mced_block(
        label="Set Tile Position to [pos]",
        pos={'label': 'Position'}
    )
    def set_tile_pos(self, pos: 'Vec3'):
        self.mcplayer.mj.player.setTilePos(float(pos.x), float(pos.y), float(pos.z))

    @mced_block(
        label="Get Direction"
    )
    def get_direction(self) -> 'Vec3':
        return self.mcplayer.mj.player.getDirection()

    @mced_block(
        label="Set Direction to [dir]",
        dir={'label': 'Direction Vector'}
    )
    def set_direction(self, dir: 'Vec3'):
        self.mcplayer.mj.player.setDirection(float(dir.x), float(dir.y), float(dir.z))

    @mced_block(
        label="Get Rotation"
    )
    def get_rotation(self) -> 'float':
        return self.mcplayer.mj.player.getRotation()

    @mced_block(
        label="Set Rotation to [yaw]",
        yaw={'label': 'Yaw'}
    )
    def set_rotation(self, yaw: 'float'):
        self.mcplayer.mj.player.setRotation(float(yaw))

    @mced_block(
        label="Get Pitch"
    )
    def get_pitch(self) -> 'float':
        return self.mcplayer.mj.player.getPitch()

    @mced_block(
        label="Set Pitch to [pitch]",
        pitch={'label': 'Pitch'}
    )
    def set_pitch(self, pitch: 'float'):
        self.mcplayer.mj.player.setPitch(float(pitch))

    @mced_block(
        label="Get Health"
    )
    def get_health(self) -> 'float':
        """Returns the health of the player."""
        return self.mcplayer.mj.player.getHealth()

    @mced_block(
        label="Set Health to [health]",
        health={'label': 'Health'}
    )
    def set_health(self, health: 'float'):
        self.mcplayer.mj.player.setHealth(float(health))

    @mced_block(
        label="Get Food Level"
    )
    def get_food_level(self) -> 'int':
        """Returns the food level of the player."""
        return self.mcplayer.mj.player.getFoodLevel()

    @mced_block(
        label="Set Food Level to [level]",
        level={'label': 'Food Level'}
    )
    def set_food_level(self, level: 'int'):
        self.mcplayer.mj.player.setFoodLevel(int(level))

    @mced_block(
        label="Send Title to Screen",
        title={'label': 'Title'},
        subtitle={'label': 'Subtitle'},
        stay={'label': 'Stay (Ticks)', 'shadow': '<shadow type="math_number"><field name="NUM">70</field></shadow>'}
    )
    def send_title(self, title: 'str', subtitle: 'str', stay: 'int'):
        """Sends a title and subtitle to the player's screen."""
        self.mcplayer.mj.player.sendTitle(str(title), str(subtitle), int(stay))

class GeneratedWorldActions(MCActionsBase):
    def __init__(self, mc_player_instance, delay_between_blocks=0):
        super().__init__(mc_player_instance, delay_between_blocks)

    @mced_block(
        label="Get Block at [position]",
        position={'label': 'Position'}
    )
    def get_block(self, position: 'Vec3') -> 'Block':
        """Returns the Block ID at the specified position."""
        return self.mcplayer.mj.world.getBlock(int(position.x), int(position.y), int(position.z))

    @mced_block(
        label="Set Block [block_type] at [position]",
        position={'label': 'Position'},
        block_type={'label': 'Block'}
    )
    def set_block(self, position: 'Vec3', block_type: 'Block'):
        """Sets a block at the specified position."""
        self.mcplayer.mj.world.setBlock(int(position.x), int(position.y), int(position.z), str(block_type))

    @mced_block(
        label="Get Blocks from [pos1] to [pos2]",
        pos1={'label': 'From Position'},
        pos2={'label': 'To Position'}
    )
    def get_blocks(self, pos1: 'Vec3', pos2: 'Vec3') -> 'list':
        """Returns a list of Block IDs in the specified area."""
        return self.mcplayer.mj.world.getBlocks(int(pos1.x), int(pos1.y), int(pos1.z), int(pos2.x), int(pos2.y), int(pos2.z))

    @mced_block(
        label="Set Blocks [block_type] from [pos1] to [pos2]",
        pos1={'label': 'From Position'},
        pos2={'label': 'To Position'},
        block_type={'label': 'Block'}
    )
    def set_blocks(self, pos1: 'Vec3', pos2: 'Vec3', block_type: 'Block'):
        """Fills a cuboid area with the specified block."""
        self.mcplayer.mj.world.setBlocks(int(pos1.x), int(pos1.y), int(pos1.z), int(pos2.x), int(pos2.y), int(pos2.z), str(block_type))

    @mced_block(
        label="Get Highest Block Y at X: [x] Z: [z]",
        x={'label': 'X'},
        z={'label': 'Z'}
    )
    def get_height(self, x: 'float', z: 'float') -> 'int':
        """Gets the Y coordinate of the highest solid block at X, Z."""
        return self.mcplayer.mj.world.getHeight(int(x), int(z))

    @mced_block(
        label="Spawn [entity_id] at [position]",
        position={'label': 'Position'},
        entity_id={'label': 'Entity'}
    )
    def spawn_entity(self, position: 'Vec3', entity_id: 'Entity') -> 'int':
        """Spawns an entity at a given position and returns its unique ID."""
        return self.mcplayer.mj.world.spawnEntity(float(position.x), float(position.y), float(position.z), str(entity_id))

    @mced_block(
        label="Remove Entity [entity_id]",
        entity_id={'label': 'Entity ID'}
    )
    def remove_entity(self, entity_id: 'int'):
        """Removes the entity with the specified ID from the world."""
        self.mcplayer.mj.world.removeEntity(int(entity_id))

    @mced_block(
        label="Get Entities in [radius] block radius from [position]",
        position={'label': 'Position'},
        radius={'label': 'Radius'}
    )
    def get_entities_in_radius(self, position: 'Vec3', radius: 'float') -> 'list':
        """Returns a list of entity IDs within a radius of a position."""
        return self.mcplayer.mj.world.getEntitiesInRadius(float(position.x), float(position.y), float(position.z), float(radius))

    @mced_block(
        label="Create Explosion power [power] at [pos]",
        pos={'label': 'Position'},
        power={'label': 'Power'}
    )
    def create_explosion(self, pos: 'Vec3', power: 'float'):
        self.mcplayer.mj.world.createExplosion(float(pos.x), float(pos.y), float(pos.z), float(power))

    @mced_block(
        label="Set Sign Text",
        position={'label': 'At Position'},
        line1={'label': 'Line 1'},
        line2={'label': 'Line 2'},
        line3={'label': 'Line 3'},
        line4={'label': 'Line 4'},
        sign_type={'label': 'Sign Material', 'shadow': 'minecraft_log_picker'},
        direction={'label': 'Direction (0-15)'}
    )
    def set_sign(self, position: 'Vec3', line1: 'str', line2: 'str', line3: 'str', line4: 'str', sign_type: 'Block', direction: 'int'):
        """Sets the text and type of a sign at the specified position."""
        self.mcplayer.mj.world.setSign(int(position.x), int(position.y), int(position.z), str(sign_type), int(direction), str(line1), str(line2), str(line3), str(line4))

    @mced_block(
        label="Drop [amount] [item] at [pos]",
        pos={'label': 'Position'},
        item={'label': 'Item'},
        amount={'label': 'Amount'}
    )
    def drop_item(self, pos: 'Vec3', item: 'Item', amount: 'int'):
        """Drops a specific item on the ground at the position."""
        self.mcplayer.mj.world.dropItem(float(pos.x), float(pos.y), float(pos.z), str(item), int(amount))

    @mced_block(
        label="Drop Random Loot at [pos]",
        pos={'label': 'Position'}
    )
    def drop_random_loot(self, pos: 'Vec3'):
        """Drops a random high-value item at the specified position."""
        self.mcplayer.mj.world.dropRandomLoot(float(pos.x), float(pos.y), float(pos.z))

    @mced_block(
        label="In container at [pos] set slot [slot] to [amount] [item]",
        pos={'label': 'Position'},
        slot={'label': 'Slot (0-26)'},
        item={'label': 'Item'},
        amount={'label': 'Amount'}
    )
    def set_container_item(self, pos: 'Vec3', slot: 'int', item: 'Item', amount: 'int'):
        """Sets an item in a chest, barrel, or hopper inventory slot."""
        self.mcplayer.mj.world.setContainerItem(int(pos.x), int(pos.y), int(pos.z), int(slot), str(item), int(amount))

class GeneratedChatActions(MCActionsBase):
    def __init__(self, mc_player_instance, delay_between_blocks=0):
        super().__init__(mc_player_instance, delay_between_blocks)

    @mced_block(
        label="Post to Chat",
        message={'label': 'Message'}
    )
    def post(self, message: 'str'):
        self.mcplayer.mj.chat.post(str(message))