from mcshell.mcjuiceconn import MCJuiceConnection
from mcshell.Vec3 import Vec3

# --- THIS FILE IS GENERATED BY THE REGISTRY BUILDER ---

class MCJuiceClient:
    def __init__(self, conn, entity_id=None):
        self.conn = conn
        self.entity_id = entity_id
        self.player = PlayerNamespace(conn, entity_id)
        self.world = WorldNamespace(conn, entity_id)
        self.chat = ChatNamespace(conn, entity_id)
        self.events = EventsNamespace(conn)

    @staticmethod
    def create(address='localhost', port=4721, playerName=''):
        conn = MCJuiceConnection(address, port); eid = None
        if playerName: eid = int(conn.sendReceive('world.getPlayerId', playerName))
        return MCJuiceClient(conn, eid)

class PlayerNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def getPos(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getPos', eid)
        return Vec3(*list(map(float, res.split(','))))

    def setPos(self, x, y, z, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.setPos', eid, x, y, z)
        return res

    def getTilePos(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getTilePos', eid)
        return Vec3(*list(map(int, res.split(','))))

    def setTilePos(self, x, y, z, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.setTilePos', eid, x, y, z)
        return res

    def getDirection(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getDirection', eid)
        return Vec3(*list(map(float, res.split(','))))

    def getRotation(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getRotation', eid)
        return float(res)

    def getPitch(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getPitch', eid)
        return float(res)

    def getHealth(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getHealth', eid)
        return float(res)

    def setHealth(self, health, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.setHealth', eid, health)
        return res

    def getFoodLevel(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getFoodLevel', eid)
        return int(res)

    def sendTitle(self, title, subtitle, stay, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.sendTitle', eid, title, subtitle, stay)
        return res

class WorldNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def getBlock(self, x, y, z):
        res = self.conn.sendReceive('world.getBlock', x, y, z)
        return res

    def setBlock(self, x, y, z, block):
        res = self.conn.sendReceive('world.setBlock', x, y, z, block)
        return res

    def getBlocks(self, x1, y1, z1, x2, y2, z2):
        res = self.conn.sendReceive('world.getBlocks', x1, y1, z1, x2, y2, z2)
        return res.split(',')

    def setBlocks(self, x1, y1, z1, x2, y2, z2, block):
        res = self.conn.sendReceive('world.setBlocks', x1, y1, z1, x2, y2, z2, block)
        return res

    def getHeight(self, x, z):
        res = self.conn.sendReceive('world.getHeight', x, z)
        return int(res)

    def getPlayerId(self, name):
        res = self.conn.sendReceive('world.getPlayerId', name)
        return int(res)

    def spawnEntity(self, x, y, z, type):
        res = self.conn.sendReceive('world.spawnEntity', x, y, z, type)
        return int(res)

    def removeEntity(self, id):
        res = self.conn.sendReceive('world.removeEntity', id)
        return res

    def getEntitiesInRadius(self, x, y, z, r):
        res = self.conn.sendReceive('world.getEntitiesInRadius', x, y, z, r)
        return res.split(',')

    def createExplosion(self, x, y, z, power):
        res = self.conn.sendReceive('world.createExplosion', x, y, z, power)
        return res

    def setSign(self, x, y, z, sign_type, direction, l1, l2, l3, l4):
        res = self.conn.sendReceive('world.setSign', x, y, z, sign_type, direction, l1, l2, l3, l4)
        return res

    def dropItem(self, x, y, z, item, amount):
        res = self.conn.sendReceive('world.dropItem', x, y, z, item, amount)
        return res

    def dropRandomLoot(self, x, y, z):
        res = self.conn.sendReceive('world.dropRandomLoot', x, y, z)
        return res

    def setContainerItem(self, x, y, z, slot, item, amount):
        res = self.conn.sendReceive('world.setContainerItem', x, y, z, slot, item, amount)
        return res

class ChatNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def post(self, message):
        res = self.conn.sendReceive('chat.post', message)
        return res

class EventsNamespace:
    def __init__(self, conn):
        self.conn = conn

    def poll(self, event_name: str):
        res = self.conn.sendReceive('events.poll', event_name)
        from mcshell.event import EventFactory
        events = [e for e in res.split('|') if e]
        return [EventFactory.create(event_name, e) for e in events]

    def clearAll(self):
        self.conn.sendReceive('events.clear')

    def pollBlockHits(self):
        return self.poll('blockHit')

    def pollChatPosts(self):
        return self.poll('chat')

    def pollArrowHits(self):
        return self.poll('arrowHit')