from mcshell.mcjuiceconn import MCJuiceConnection
from mcshell.Vec3 import Vec3

# --- THIS FILE IS GENERATED BY THE REGISTRY BUILDER ---

class MCJuiceClient:
    def __init__(self, conn, entity_id=None):
        self.conn = conn
        self.entity_id = entity_id
        self.player = PlayerNamespace(conn, entity_id)

    @staticmethod
    def create(address='localhost', port=4721, playerName='') -> 'MCJuiceClient':
        conn = MCJuiceConnection(address, port)
        entity_id = None
        if playerName != '':
            try:
                res = conn.sendReceive('world.getPlayerId', playerName)
                entity_id = int(res)
            except Exception:
                entity_id = None
        return MCJuiceClient(conn, entity_id)

class PlayerNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def getPos(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.getPos', eid)
        return Vec3(*list(map(float, res.split(','))))

    def setPos(self, x, y, z, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.setPos', eid, x, y, z)
        return res

    def getDirection(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.getDirection', eid)
        return Vec3(*list(map(float, res.split(','))))

    def getRotation(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.getRotation', eid)
        return float(res)

    def getPitch(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.getPitch', eid)
        return float(res)

    def getHealth(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.getHealth', eid)
        return float(res)

    def setHealth(self, health, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.setHealth', eid, health)
        return res

    def getFoodLevel(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.getFoodLevel', eid)
        return int(res)

    def setFoodLevel(self, level, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.setFoodLevel', eid, level)
        return res

    def sendMessage(self, message, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id provided or resolved.')
        res = self.conn.sendReceive('player.sendMessage', eid, message)
        return res