from mcshell.mcjuiceconn import MCJuiceConnection
from mcshell.Vec3 import Vec3

# --- THIS FILE IS GENERATED BY THE REGISTRY BUILDER ---

class MCJuiceClient:
    def __init__(self, conn, entity_id=None):
        self.conn = conn
        self.entity_id = entity_id
        self.player = PlayerNamespace(conn, entity_id)
        self.world = WorldNamespace(conn, entity_id)
        self.chat = ChatNamespace(conn, entity_id)
        self.events = EventsNamespace(conn)

    @staticmethod
    def create(address='localhost', port=4721, playerName=''):
        conn = MCJuiceConnection(address, port); eid = None
        if playerName: eid = int(conn.sendReceive('world.getPlayerId', playerName))
        return MCJuiceClient(conn, eid)

class PlayerNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def getPos(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getPos', eid)
        return Vec3(*list(map(float, res.split(','))))

    def setPos(self, x, y, z, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setPos', eid, x, y, z)
        return 'OK'

    def getTilePos(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getTilePos', eid)
        return Vec3(*list(map(int, res.split(','))))

    def setTilePos(self, x, y, z, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setTilePos', eid, x, y, z)
        return 'OK'

    def getDirection(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getDirection', eid)
        return Vec3(*list(map(float, res.split(','))))

    def setDirection(self, x, y, z, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setDirection', eid, x, y, z)
        return 'OK'

    def getRotation(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getRotation', eid)
        return float(res)

    def setRotation(self, yaw, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setRotation', eid, yaw)
        return 'OK'

    def getPitch(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getPitch', eid)
        return float(res)

    def setPitch(self, pitch, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setPitch', eid, pitch)
        return 'OK'

    def getHealth(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getHealth', eid)
        return float(res)

    def setHealth(self, health, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setHealth', eid, health)
        return 'OK'

    def getFoodLevel(self, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        res = self.conn.sendReceive('player.getFoodLevel', eid)
        return int(res)

    def setFoodLevel(self, level, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.setFoodLevel', eid, level)
        return 'OK'

    def sendTitle(self, title, subtitle, stay, entity_id=None):
        eid = entity_id if entity_id is not None else self.entity_id
        if eid is None: raise ValueError('No entity_id')
        self.conn.send('player.sendTitle', eid, title, subtitle, stay)
        return 'OK'

class WorldNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def getBlock(self, x, y, z):
        res = self.conn.sendReceive('world.getBlock', x, y, z)
        return res

    def setBlock(self, x, y, z, block):
        self.conn.send('world.setBlock', x, y, z, block)
        return 'OK'

    def getBlocks(self, x1, y1, z1, x2, y2, z2):
        res = self.conn.sendReceive('world.getBlocks', x1, y1, z1, x2, y2, z2)
        return res.split(',')

    def setBlocks(self, x1, y1, z1, x2, y2, z2, block):
        self.conn.send('world.setBlocks', x1, y1, z1, x2, y2, z2, block)
        return 'OK'

    def getHeight(self, x, z):
        res = self.conn.sendReceive('world.getHeight', x, z)
        return int(res)

    def getPlayerId(self, name):
        res = self.conn.sendReceive('world.getPlayerId', name)
        return int(res)

    def spawnEntity(self, x, y, z, type):
        res = self.conn.sendReceive('world.spawnEntity', x, y, z, type)
        return int(res)

    def removeEntity(self, id):
        self.conn.send('world.removeEntity', id)
        return 'OK'

    def getEntitiesInRadius(self, x, y, z, r):
        res = self.conn.sendReceive('world.getEntitiesInRadius', x, y, z, r)
        return res.split(',')

    def createExplosion(self, x, y, z, power):
        self.conn.send('world.createExplosion', x, y, z, power)
        return 'OK'

    def setSign(self, x, y, z, sign_type, direction, l1, l2, l3, l4):
        self.conn.send('world.setSign', x, y, z, sign_type, direction, l1, l2, l3, l4)
        return 'OK'

    def dropItem(self, x, y, z, item, amount):
        self.conn.send('world.dropItem', x, y, z, item, amount)
        return 'OK'

    def dropRandomLoot(self, x, y, z):
        self.conn.send('world.dropRandomLoot', x, y, z)
        return 'OK'

    def setContainerItem(self, x, y, z, slot, item, amount):
        self.conn.send('world.setContainerItem', x, y, z, slot, item, amount)
        return 'OK'

class ChatNamespace:
    def __init__(self, conn, entity_id):
        self.conn = conn
        self.entity_id = entity_id

    def post(self, message):
        self.conn.send('chat.post', message)
        return 'OK'

class EventsNamespace:
    def __init__(self, conn):
        self.conn = conn

    def poll(self, event_name: str):
        res = self.conn.sendReceive('events.poll', event_name)
        if res == 'OK' or not res: return []
        from mcshell.event import EventFactory
        events = [e for e in res.split('|') if e and ',' in e]
        return [EventFactory.create(event_name, e) for e in events]

    def clearAll(self):
        self.conn.sendReceive('events.clear')

    def pollRightBlockHits(self):
        return self.poll('rightBlockHit')

    def pollLeftBlockHits(self):
        return self.poll('leftBlockHit')

    def pollBlockPlaces(self):
        return self.poll('blockPlace')

    def pollBlockBreaks(self):
        return self.poll('blockBreak')

    def pollChats(self):
        return self.poll('chat')

    def pollProjectileHitBlocks(self):
        return self.poll('projectileHitBlock')

    def pollProjectileHitEntitys(self):
        return self.poll('projectileHitEntity')

    def pollProjectileLaunchs(self):
        return self.poll('projectileLaunch')